#!/usr/bin/env bash
# ============================================================================
#
#  OLDFILES INSTALLER
#
#  File:        install.sh
#  Version:     1.0.0
#  License:     MIT
#  Requires:    macOS or Linux, bash 3.2+, python3
#
#  Description:
#    Installs the `oldfiles` command to ~/.local/bin (user-local, no sudo) or
#    /usr/local/bin (system-wide, requires sudo). Also creates a local .venv
#    next to the script with Send2Trash, so the recoverable `--delete` (Trash)
#    action works instantly the first time. Listing and `--delete-permanent`
#    are pure stdlib and need no venv.
#
#    The installed `oldfiles` is a thin launcher that execs this repo's
#    oldfiles.py with the system python3; the script self-bootstraps the .venv
#    when (and only when) Trash support is needed.
#
#  Usage:
#    ./install.sh              Install to ~/.local/bin (default, no sudo)
#    ./install.sh --system     Install to /usr/local/bin (requires sudo)
#    ./install.sh --upgrade    Re-run install (refresh launcher + venv deps)
#    ./install.sh --uninstall  Remove the launcher (leaves your repo checkout)
#    ./install.sh --help       Show this help
#
# ============================================================================

set -euo pipefail

TOOL_NAME="oldfiles"
TOOL_CMD="oldfiles"
SCRIPT_FILE="oldfiles.py"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE="${SCRIPT_DIR}/${SCRIPT_FILE}"

USER_BIN="${HOME}/.local/bin"
SYSTEM_BIN="/usr/local/bin"
INSTALL_DIR="${USER_BIN}"   # overridden by --system

# ─── Colour helpers ─────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
    C_RESET="\033[0m"; C_BOLD="\033[1m"
    C_GREEN="\033[32m"; C_YELLOW="\033[33m"; C_RED="\033[31m"; C_CYAN="\033[36m"
else
    C_RESET=""; C_BOLD=""; C_GREEN=""; C_YELLOW=""; C_RED=""; C_CYAN=""
fi
info()    { printf "${C_CYAN}  →${C_RESET} %s\n" "$*"; }
success() { printf "${C_GREEN}  ✓${C_RESET} %s\n" "$*"; }
warn()    { printf "${C_YELLOW}  ⚠${C_RESET} %s\n" "$*" >&2; }
die()     { printf "${C_RED}  ✗ error:${C_RESET} %s\n" "$*" >&2; exit 1; }
header()  { printf "\n${C_BOLD}%s${C_RESET}\n" "$*"; }

# ─── Argument parsing ────────────────────────────────────────────────────────
MODE="install"
for arg in "$@"; do
    case "$arg" in
        --system)    INSTALL_DIR="${SYSTEM_BIN}" ;;
        --upgrade)   MODE="upgrade" ;;
        --uninstall) MODE="uninstall" ;;
        --help|-h)
            sed -n '2,33p' "${BASH_SOURCE[0]}" | sed 's/^#\s\?//'
            exit 0 ;;
        *) die "Unknown argument: $arg (see --help)" ;;
    esac
done

TARGET="${INSTALL_DIR}/${TOOL_CMD}"

uninstall() {
    header "Uninstalling ${TOOL_NAME}"
    if [[ -e "${TARGET}" ]]; then
        rm -f "${TARGET}" && success "Removed ${TARGET}"
    else
        warn "No launcher found at ${TARGET}"
    fi
    info "Your repo checkout and its .venv were left in place."
    exit 0
}
[[ "${MODE}" == "uninstall" ]] && uninstall

# ─── Install ─────────────────────────────────────────────────────────────────
header "Installing ${TOOL_NAME} ${MODE:+($MODE)}"

command -v python3 >/dev/null 2>&1 || die "python3 not found on PATH."
[[ -f "${SOURCE}" ]] || die "Cannot find ${SOURCE}"

# 1. Pre-create the .venv with Send2Trash (so the first `--delete` is instant).
VENV="${SCRIPT_DIR}/.venv"
info "Setting up Trash support venv (Send2Trash)…"
python3 -m venv "${VENV}"
"${VENV}/bin/python3" -m pip install -q --upgrade pip
"${VENV}/bin/python3" -m pip install -q -r "${SCRIPT_DIR}/requirements.txt"
success "venv ready at ${VENV}"

# 2. Install the launcher.
mkdir -p "${INSTALL_DIR}" 2>/dev/null || die "Cannot create ${INSTALL_DIR} (try --system with sudo)."
cat > "${TARGET}" <<EOF
#!/usr/bin/env bash
# oldfiles launcher (generated by install.sh) — runs the repo script.
exec python3 "${SOURCE}" "\$@"
EOF
chmod +x "${TARGET}" || die "Cannot write ${TARGET} (try --system with sudo)."
success "Installed launcher: ${TARGET}"

# 3. PATH hint.
case ":${PATH}:" in
    *":${INSTALL_DIR}:"*) ;;
    *) warn "${INSTALL_DIR} is not on your PATH. Add it, e.g.:"
       printf "      echo 'export PATH=\"%s:\$PATH\"' >> ~/.zshrc\n" "${INSTALL_DIR}" ;;
esac

header "Done"
info  "Try it (safe — dry run, deletes nothing):"
printf "      %s ~/Downloads --older-than 1y\n" "${TOOL_CMD}"
