// GENERATED by scripts/embed-fonts.mjs — do not edit by hand.
// Font metadata (display label, CSS family, category, available styles).

export interface EmbeddedFontMeta {
  key: string;
  label: string;
  cssFamily: string;
  category: 'sans' | 'serif' | 'script' | 'display' | 'handwriting' | 'mono';
  styles: string[];
}

export const FONT_REGISTRY: EmbeddedFontMeta[] = [
  {
    "key": "inter",
    "label": "Inter",
    "cssFamily": "CM Inter",
    "category": "sans",
    "styles": [
      "normal",
      "bold"
    ]
  },
  {
    "key": "montserrat",
    "label": "Montserrat",
    "cssFamily": "CM Montserrat",
    "category": "sans",
    "styles": [
      "normal",
      "bold"
    ]
  },
  {
    "key": "nunito",
    "label": "Nunito",
    "cssFamily": "CM Nunito",
    "category": "sans",
    "styles": [
      "normal",
      "bold"
    ]
  },
  {
    "key": "lora",
    "label": "Lora",
    "cssFamily": "CM Lora",
    "category": "serif",
    "styles": [
      "normal",
      "bold"
    ]
  },
  {
    "key": "merriweather",
    "label": "Merriweather",
    "cssFamily": "CM Merriweather",
    "category": "serif",
    "styles": [
      "normal",
      "bold"
    ]
  },
  {
    "key": "playfair",
    "label": "Playfair Display",
    "cssFamily": "CM Playfair",
    "category": "serif",
    "styles": [
      "normal",
      "bold"
    ]
  },
  {
    "key": "caveat",
    "label": "Caveat",
    "cssFamily": "CM Caveat",
    "category": "handwriting",
    "styles": [
      "normal",
      "bold"
    ]
  },
  {
    "key": "dancing",
    "label": "Dancing Script",
    "cssFamily": "CM Dancing Script",
    "category": "script",
    "styles": [
      "normal",
      "bold"
    ]
  },
  {
    "key": "pacifico",
    "label": "Pacifico",
    "cssFamily": "CM Pacifico",
    "category": "display",
    "styles": [
      "normal"
    ]
  }
];
