// GENERATED by scripts/ingest-content.mjs — do not edit by hand.
// Source: /Users/bronty13/Downloads/tlc_quotes_seed.json
// 17 sayings.

import type { FillerEntry } from '../model/types';

export const SAYINGS: FillerEntry[] = [
  {
    "id": "tlc-001",
    "kind": "saying",
    "text": "He's where the joy is.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-002",
    "kind": "saying",
    "text": "God is where the joy is.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-003",
    "kind": "saying",
    "text": "There's no such thing as being behind. Every day that you're in God's word, you're right on time.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-004",
    "kind": "saying",
    "text": "The beauty of the gospel is that my salvation, my security, and my relationship with God don't rest on my best efforts. It rests on Christ's finished work.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-005",
    "kind": "saying",
    "text": "Community happens best when it is the byproduct of being on mission together.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-006",
    "kind": "saying",
    "text": "I didn't just want people to read it, I wanted them to understand it. I wanted them to love it.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-007",
    "kind": "saying",
    "text": "Never did I imagine the No. 1 spot in Christian podcasts, much less all podcasts.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-008",
    "kind": "saying",
    "text": "He's after their joy and he's where the joy is. If he's pursuing them to know him more, there is joy for them in that.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-009",
    "kind": "saying",
    "text": "Out of all the Ten Commandments, there are two He keeps repeating: You shall have no other gods before Me, and rest.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-010",
    "kind": "saying",
    "text": "Knowledge is having the facts. Understanding is the ability to discern what the facts mean and how they fit together in the big picture. Wisdom is knowing how to apply your knowledge and understanding, translating it into the everyday life of a Christ follower.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-011",
    "kind": "saying",
    "text": "Contrary to popular thought, God doesn't undergo a personality transplant at the end of the Old Testament.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-012",
    "kind": "saying",
    "text": "I want to live and die with the Word of God on my lips. It directs me when I'm confused. It corrects me when I'm wrong. It comforts me when I'm aching.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-013",
    "kind": "saying",
    "text": "Read the Word. It will change your life.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-014",
    "kind": "saying",
    "text": "Read Scripture looking for God's character rather than for rules or self-improvement, and it becomes transformative.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-015",
    "kind": "saying",
    "text": "It's hard to love a God we don't know, and it's hard to know a God we don't understand.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-016",
    "kind": "saying",
    "text": "Without the Trinity, there is no gospel.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-017",
    "kind": "saying",
    "text": "Disciples making disciple-making disciples.",
    "reference": "Tara-Leigh Cobble"
  }
];
