// GENERATED by scripts/ingest-content.mjs — do not edit by hand.
// Sources: /Users/bronty13/Downloads/tlc_quotes_seed.json
//          /Users/bronty13/Downloads/affirmations/*.docx
// 40 sayings (17 quotes + 23 affirmations).

import type { FillerEntry } from '../model/types';

export const SAYINGS: FillerEntry[] = [
  {
    "id": "tlc-001",
    "kind": "saying",
    "text": "He's where the joy is.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-002",
    "kind": "saying",
    "text": "God is where the joy is.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-003",
    "kind": "saying",
    "text": "There's no such thing as being behind. Every day that you're in God's word, you're right on time.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-004",
    "kind": "saying",
    "text": "The beauty of the gospel is that my salvation, my security, and my relationship with God don't rest on my best efforts. It rests on Christ's finished work.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-005",
    "kind": "saying",
    "text": "Community happens best when it is the byproduct of being on mission together.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-006",
    "kind": "saying",
    "text": "I didn't just want people to read it, I wanted them to understand it. I wanted them to love it.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-007",
    "kind": "saying",
    "text": "Never did I imagine the No. 1 spot in Christian podcasts, much less all podcasts.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-008",
    "kind": "saying",
    "text": "He's after their joy and he's where the joy is. If he's pursuing them to know him more, there is joy for them in that.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-009",
    "kind": "saying",
    "text": "Out of all the Ten Commandments, there are two He keeps repeating: You shall have no other gods before Me, and rest.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-010",
    "kind": "saying",
    "text": "Knowledge is having the facts. Understanding is the ability to discern what the facts mean and how they fit together in the big picture. Wisdom is knowing how to apply your knowledge and understanding, translating it into the everyday life of a Christ follower.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-011",
    "kind": "saying",
    "text": "Contrary to popular thought, God doesn't undergo a personality transplant at the end of the Old Testament.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-012",
    "kind": "saying",
    "text": "I want to live and die with the Word of God on my lips. It directs me when I'm confused. It corrects me when I'm wrong. It comforts me when I'm aching.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-013",
    "kind": "saying",
    "text": "Read the Word. It will change your life.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-014",
    "kind": "saying",
    "text": "Read Scripture looking for God's character rather than for rules or self-improvement, and it becomes transformative.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-015",
    "kind": "saying",
    "text": "It's hard to love a God we don't know, and it's hard to know a God we don't understand.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-016",
    "kind": "saying",
    "text": "Without the Trinity, there is no gospel.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "tlc-017",
    "kind": "saying",
    "text": "Disciples making disciple-making disciples.",
    "reference": "Tara-Leigh Cobble"
  },
  {
    "id": "affirm-001",
    "kind": "saying",
    "text": "Jesus is first in my life. I exist to serve and glorify Him.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-002",
    "kind": "saying",
    "text": "I love people (Romans 12:10) and believe the best about others even when inclined to do otherwise.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-003",
    "kind": "saying",
    "text": "I am disciplined. (1 Thessalonians 4:4) Christ in me is stronger (Romans 7:24-25) than the wrong desires in me.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-004",
    "kind": "saying",
    "text": "I am growing closer to Jesus (2 Peter 3:18) every day. Because of Christ, my family is closer, my body is stronger, my faith is deeper, and my leadership is sharper.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-005",
    "kind": "saying",
    "text": "I am anointed, empowered, equipped, and called (Matthew 28:19-20) to reach people far from God.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-006",
    "kind": "saying",
    "text": "I am creative, innovative, driven, focused, and blessed beyond measure (Ephesians 1:3) because the Holy Spirit is inside (2 Timothy 1:14) of me.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-007",
    "kind": "saying",
    "text": "I wake up with purpose (Romans 8:28), direction, and meaning every day of my life.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-008",
    "kind": "saying",
    "text": "Pain is my friend. I rejoice in suffering (1 Peter 4:13) because Christ suffered for me.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-009",
    "kind": "saying",
    "text": "I bring my best (2 Timothy 2:15) and then some. It’s what I bring after I do my best that makes the difference.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-010",
    "kind": "saying",
    "text": "The world will be different and better because I served Jesus (2 Corinthians 5:18-19) today.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-011",
    "kind": "saying",
    "text": "I am strong and mighty. I have the same power (Ephesians 1:18-20) that raised Christ from the dead living inside of me. I am a weapon of righteousness and goodness (2 Corinthians 6:7) in a world of darkness.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-012",
    "kind": "saying",
    "text": "I am not a slave to my habits. I am not a prisoner to an addiction. I have been rescued (Colossians 1:13-14) from the power of darkness and brought into the kingdom of God’s light.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-013",
    "kind": "saying",
    "text": "I am not my past. I am not what I did. I am who God says I am. He says I am forgiven (Ephesians 1:7) He says I am redeemed. He says I am free (Galatians 5:1).",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-014",
    "kind": "saying",
    "text": "Worry is not my master. I trust in God (John 14:1) His peace guards (Philippians 4:6-7) my heart, guards my mind, and guards my soul in Christ Jesus.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-015",
    "kind": "saying",
    "text": "I have the mind of Jesus Christ (1 Corinthians 2:16) directing my thoughts. I have the Word of God guiding (Psalms 119:105) my steps.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-016",
    "kind": "saying",
    "text": "My God will bless me abundantly, so that in all things, at all times, having all I need (2 Peter 1:3) I will abound (2 Corinthians 9:8) in every good work.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-017",
    "kind": "saying",
    "text": "I love my wife (Ephesians 5:25) and will lay down my life to serve her.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-018",
    "kind": "saying",
    "text": "I love my husband (Ephesians 5:33) and will respect him.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-019",
    "kind": "saying",
    "text": "I will meet his needs as defined by him.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-020",
    "kind": "saying",
    "text": "I will never intentionally do harm to him.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-021",
    "kind": "saying",
    "text": "I can’t give him what I don’t have and that’s okay.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-022",
    "kind": "saying",
    "text": "I will always be welcoming and safe for him to express his opinions.",
    "reference": "Morning Affirmation"
  },
  {
    "id": "affirm-023",
    "kind": "saying",
    "text": "I will always attribute innocence to him.",
    "reference": "Morning Affirmation"
  }
];
