-- Phase 1.1 redesign: evolve the empty kinks tables from migration 010.
--
-- * Adds description column (each kink ships with a short definition
--   surfaced in the KinkChipPicker dropdown).
-- * Adds position column to customer_kinks so order is per-customer
--   (mirrors MasterClipper's clip_categories.position model).
-- * Preloads 349 default kinks from the curated source list — every
--   row shares the same pink color (#EC4899) because the picker shows
--   them as a flat selectable list and per-row color is meaningless.
--   sort_order = JSON-array index * 10 so the curated order survives.

ALTER TABLE kinks ADD COLUMN description TEXT NOT NULL DEFAULT '';

ALTER TABLE customer_kinks ADD COLUMN position INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS customer_kinks_by_pos ON customer_kinks(customer_uid, position);

INSERT OR IGNORE INTO kinks (name, description, color, sort_order) VALUES
    ('Voyeurism', 'Arousal from watching others who are naked or engaged in sex, consensually or not.', '#EC4899', 10),
    ('Exhibitionism', 'Arousal from exposing oneself or being watched; consensual variant is subclinical.', '#EC4899', 20),
    ('Frotteurism', 'Arousal from rubbing or pressing against another person; non-consensual form is clinical.', '#EC4899', 30),
    ('Masochism', 'Arousal from receiving pain, humiliation, or suffering.', '#EC4899', 40),
    ('Sadism', 'Arousal from inflicting pain or suffering on another.', '#EC4899', 50),
    ('Fetishism', 'Arousal centered on a non-genital object or body part.', '#EC4899', 60),
    ('Transvestism / Cross-dressing', 'Arousal from wearing clothing associated with another gender.', '#EC4899', 70),
    ('Telephone Scatologia', 'Arousal from making obscene phone calls.', '#EC4899', 80),
    ('Necrophilia', 'Sexual attraction to or fantasy involving corpses.', '#EC4899', 90),
    ('Zoophilia / Bestiality', 'Sexual attraction to or fantasy involving animals.', '#EC4899', 100),
    ('Coprophilia / Scat', 'Arousal involving feces.', '#EC4899', 110),
    ('Klismaphilia / Enemas', 'Arousal from enemas or enema scenarios.', '#EC4899', 120),
    ('Urophilia / Watersports', 'Arousal involving urine or urination.', '#EC4899', 130),
    ('Romance / Affection', 'Generalized affectionate or romantic behavior as a sexual interest.', '#EC4899', 140),
    ('Hugging', 'Physical embrace as an erotic act.', '#EC4899', 150),
    ('Kissing — Body', 'Kissing across various body parts.', '#EC4899', 160),
    ('Kissing — Mouth', 'Mouth-to-mouth kissing as an erotic focus.', '#EC4899', 170),
    ('Spooning', 'Lying close, back-to-chest, embracing from behind.', '#EC4899', 180),
    ('Cuddling', 'Non-genital close physical contact.', '#EC4899', 190),
    ('Aftercare', 'Post-scene emotional and physical care, especially in BDSM.', '#EC4899', 200),
    ('Pet Names', 'Use of affectionate or possessive nicknames during intimacy.', '#EC4899', 210),
    ('Using Real Names', 'Using a partner''s actual name rather than nicknames or titles.', '#EC4899', 220),
    ('Sleepover / Sleeping Together', 'Sharing a bed overnight with a partner as an erotic or intimate act.', '#EC4899', 230),
    ('Clothed Sex', 'Sex while partially or fully clothed.', '#EC4899', 240),
    ('Lingerie', 'Erotic focus on women''s intimate apparel.', '#EC4899', 250),
    ('Stockings / Hosiery', 'Erotic focus on stockings, tights, or pantyhose.', '#EC4899', 260),
    ('Heels / High Heels', 'Erotic focus on high-heeled footwear.', '#EC4899', 270),
    ('Leather', 'Erotic focus on leather garments or accessories.', '#EC4899', 280),
    ('Latex / Rubber', 'Erotic focus on latex or rubber clothing or full encasement.', '#EC4899', 290),
    ('Uniforms', 'Erotic focus on uniformed personas (military, medical, etc.).', '#EC4899', 300),
    ('Cosplay', 'Sexual roleplay involving costumed characters.', '#EC4899', 310),
    ('Forced Cross-dressing', 'Cross-dressing performed under simulated coercion.', '#EC4899', 320),
    ('Forced Verbal Feminization', 'Verbal humiliation framing the target as feminized.', '#EC4899', 330),
    ('Formal Wear', 'Erotic focus on formal attire such as suits or gowns.', '#EC4899', 340),
    ('Corsets', 'Erotic focus on corsetry and waist training.', '#EC4899', 350),
    ('Gloves', 'Erotic focus on gloves of various materials.', '#EC4899', 360),
    ('Jewelry', 'Erotic focus on worn jewelry or piercings.', '#EC4899', 370),
    ('Boot Aesthetics / Boot Worship', 'Erotic focus on boots and boot-related acts.', '#EC4899', 380),
    ('Underwear / Panties', 'Erotic focus on undergarments.', '#EC4899', 390),
    ('Revealing / Slutty Clothes', 'Erotic focus on overtly sexualized attire.', '#EC4899', 400),
    ('Makeup', 'Erotic focus on cosmetics.', '#EC4899', 410),
    ('One-on-One (M)', 'Sexual pairing with one male partner.', '#EC4899', 420),
    ('One-on-One (F)', 'Sexual pairing with one female partner.', '#EC4899', 430),
    ('Threesome', 'Three-person sexual encounter.', '#EC4899', 440),
    ('Orgy', 'Group sex involving multiple participants.', '#EC4899', 450),
    ('Gangbang', 'One person with multiple partners simultaneously.', '#EC4899', 460),
    ('Harem', 'Power fantasy involving one person with a stable group.', '#EC4899', 470),
    ('Spitroasting', 'One person penetrated by two others from opposite ends.', '#EC4899', 480),
    ('Double Penetration (DP)', 'Two simultaneous penetrations of one person.', '#EC4899', 490),
    ('Glory Hole', 'Anonymous sex through an opening in a wall.', '#EC4899', 500),
    ('Open Relationships', 'Consensual non-monogamy.', '#EC4899', 510),
    ('Polyamory', 'Multiple concurrent romantic or sexual relationships.', '#EC4899', 520),
    ('Cuckolding / Cuckqueaning', 'Arousal from watching a partner have sex with someone else.', '#EC4899', 530),
    ('Hotwife / Stag', 'Cuckold variant emphasizing the partner''s autonomy and enjoyment.', '#EC4899', 540),
    ('Swinging', 'Couples recreationally exchanging partners.', '#EC4899', 550),
    ('Vaginal Sex', 'Penile-vaginal intercourse.', '#EC4899', 560),
    ('Anal Sex', 'Anal penetration.', '#EC4899', 570),
    ('Pegging', 'Strap-on anal penetration of a male partner by a woman.', '#EC4899', 580),
    ('Strap-on Penetration', 'Use of a strap-on dildo for penetration.', '#EC4899', 590),
    ('Barebacking', 'Unprotected penetrative sex.', '#EC4899', 600),
    ('Handjobs / Fingering', 'Manual genital stimulation.', '#EC4899', 610),
    ('Blowjobs / Fellatio', 'Oral stimulation of the penis.', '#EC4899', 620),
    ('Cunnilingus', 'Oral stimulation of the vulva or clitoris.', '#EC4899', 630),
    ('Rimming / Analingus', 'Oral stimulation of the anus.', '#EC4899', 640),
    ('Deep Throating', 'Taking a penis deeply into the throat during oral sex.', '#EC4899', 650),
    ('Face Fucking', 'Active thrusting into a partner''s mouth.', '#EC4899', 660),
    ('Face Sitting', 'Sitting on a partner''s face for oral stimulation.', '#EC4899', 670),
    ('Facials', 'Ejaculating onto a partner''s face.', '#EC4899', 680),
    ('Bukkake', 'Multiple partners ejaculating onto one person.', '#EC4899', 690),
    ('69 / Sixty-Nining', 'Simultaneous mutual oral sex.', '#EC4899', 700),
    ('Tribadism / Scissoring', 'Vulva-on-vulva genital friction.', '#EC4899', 710),
    ('Intercrural / Interfemoral Sex', 'Penile stimulation between a partner''s thighs.', '#EC4899', 720),
    ('Frottage / Grinding / Dry Humping', 'Clothed rubbing or grinding for sexual stimulation.', '#EC4899', 730),
    ('Titty Fucking / Mammary Intercourse', 'Penile stimulation between the breasts.', '#EC4899', 740),
    ('Footjob', 'Genital stimulation using the feet.', '#EC4899', 750),
    ('Masturbation (Solo)', 'Self-stimulation for arousal or orgasm.', '#EC4899', 760),
    ('Mutual Masturbation', 'Partners masturbating together or each other.', '#EC4899', 770),
    ('Fisting — Anal', 'Insertion of a hand into the anus.', '#EC4899', 780),
    ('Fisting — Vaginal', 'Insertion of a hand into the vagina.', '#EC4899', 790),
    ('Object Insertion', 'Insertion of non-genital objects vaginally or anally.', '#EC4899', 800),
    ('Cockwarming', 'Penetration held still without active thrusting.', '#EC4899', 810),
    ('Cock Milking', 'Repeated or prolonged stimulation to draw out ejaculation.', '#EC4899', 820),
    ('Public Sex', 'Sex in public or semi-public spaces.', '#EC4899', 830),
    ('Exhibitionism (Consensual)', 'Arousal from being watched by a consenting audience.', '#EC4899', 840),
    ('Voyeurism (Consensual)', 'Arousal from watching consenting others.', '#EC4899', 850),
    ('Car Sex', 'Sex inside an automobile.', '#EC4899', 860),
    ('Shower / Bath / Pool Sex', 'Sex in water or wet environments.', '#EC4899', 870),
    ('Phone Sex / Sexting', 'Sexual communication via phone or text.', '#EC4899', 880),
    ('Sex Against a Wall', 'Standing sex with a partner pressed against a wall.', '#EC4899', 890),
    ('Mirror Sex', 'Sex while watching oneself or the scene in a mirror.', '#EC4899', 900),
    ('Almost Getting Caught', 'Arousal from the risk of being discovered.', '#EC4899', 910),
    ('Getting Caught', 'Arousal from actually being discovered during sex.', '#EC4899', 920),
    ('Angry Sex / Hatefucking', 'Sex framed by hostility or conflict.', '#EC4899', 930),
    ('Gentle Sex', 'Slow, tender sex emphasizing intimacy.', '#EC4899', 940),
    ('Rough Sex', 'Aggressive physicality within sex.', '#EC4899', 950),
    ('Drunk / Intoxicated Sex', 'Sex while one or both parties are intoxicated.', '#EC4899', 960),
    ('Sleepy / Morning Sex', 'Sex while drowsy or immediately upon waking.', '#EC4899', 970),
    ('Distracted / Distant Sex', 'Sex while feigning disinterest or multitasking.', '#EC4899', 980),
    ('Fake Public Use', 'Public-use fantasy enacted in a safe private setting.', '#EC4899', 990),
    ('Sweat / Hyhephilia', 'Arousal involving the smell or presence of sweat.', '#EC4899', 1000),
    ('Tears / Dacryphilia', 'Arousal from a partner''s tears.', '#EC4899', 1010),
    ('Lactation (Female)', 'Arousal involving female breast milk.', '#EC4899', 1020),
    ('Lactation (Male)', 'Arousal involving induced male lactation.', '#EC4899', 1030),
    ('Cum Play', 'Arousal from handling or displaying semen.', '#EC4899', 1040),
    ('Creampie', 'Visible internal ejaculate after withdrawal.', '#EC4899', 1050),
    ('Felching', 'Oral retrieval of ejaculate from a partner''s body.', '#EC4899', 1060),
    ('Snowballing', 'Mouth-to-mouth transfer of ejaculate between partners.', '#EC4899', 1070),
    ('Swallowing Cum', 'Ingesting semen orally.', '#EC4899', 1080),
    ('Diapers / Diaper Play', 'Use of diapers, often within ABDL or age play.', '#EC4899', 1090),
    ('Blood Play / Hematolagnia', 'Arousal involving blood.', '#EC4899', 1100),
    ('Menstrual Blood / Menophilia', 'Arousal involving menstruation.', '#EC4899', 1110),
    ('Mucophilia', 'Arousal involving nasal mucus.', '#EC4899', 1120),
    ('Emetophilia', 'Arousal involving vomit.', '#EC4899', 1130),
    ('Salirophilia / Spit', 'Arousal involving saliva, drooling, or spitting.', '#EC4899', 1140),
    ('Flatulence / Eproctophilia', 'Arousal involving flatulence.', '#EC4899', 1150),
    ('Partialism', 'Exclusive sexual focus on a specific non-genital body part.', '#EC4899', 1160),
    ('Feet / Podophilia / Foot Fetish', 'Erotic focus on feet.', '#EC4899', 1170),
    ('Hand Fetish', 'Erotic focus on hands.', '#EC4899', 1180),
    ('Armpits / Maschalagnia', 'Erotic focus on armpits.', '#EC4899', 1190),
    ('Body Hair / Hirsutophilia', 'Erotic focus on body hair.', '#EC4899', 1200),
    ('Hair (Head) / Trichophilia', 'Erotic focus on head hair — color, length, or style.', '#EC4899', 1210),
    ('Hair Pulling', 'Pulling a partner''s hair during sex.', '#EC4899', 1220),
    ('Hair Brushing / Braiding', 'Sensual hair grooming as an erotic act.', '#EC4899', 1230),
    ('Hair Cutting', 'Erotic focus on cutting hair.', '#EC4899', 1240),
    ('Shaving', 'Erotic focus on shaving body hair.', '#EC4899', 1250),
    ('Nipple Play', 'Stimulation of nipples.', '#EC4899', 1260),
    ('Breast Worship', 'Reverential erotic focus on breasts.', '#EC4899', 1270),
    ('Ass Worship', 'Reverential erotic focus on buttocks.', '#EC4899', 1280),
    ('Cock Worship', 'Reverential erotic focus on the penis.', '#EC4899', 1290),
    ('Pussy / Yoni Worship', 'Reverential erotic focus on the vulva.', '#EC4899', 1300),
    ('Belly / Throat Bulge', 'Visible distension from deep oral or vaginal penetration.', '#EC4899', 1310),
    ('Anal Gaping', 'Visible anal dilation following penetration.', '#EC4899', 1320),
    ('Anal Prolapse', 'Extreme anal play resulting in tissue eversion.', '#EC4899', 1330),
    ('Inflation', 'Fantasy involving body inflation.', '#EC4899', 1340),
    ('Stuffing / Feeding', 'Force-feeding or overeating for arousal.', '#EC4899', 1350),
    ('Weight Gain / Feederism', 'Arousal from gaining weight or causing a partner to gain.', '#EC4899', 1360),
    ('Pregnancy / Maiesiophilia', 'Arousal involving pregnant bodies.', '#EC4899', 1370),
    ('Mpreg (Male Pregnancy)', 'Fictional male pregnancy trope.', '#EC4899', 1380),
    ('Forced Pregnancy', 'Coerced pregnancy scenario in fiction or fantasy.', '#EC4899', 1390),
    ('Breeding / Impregnation', 'Fantasy focused on conception or insemination.', '#EC4899', 1400),
    ('Piercings', 'Erotic focus on body piercings.', '#EC4899', 1410),
    ('Tattoos', 'Erotic focus on tattoos.', '#EC4899', 1420),
    ('Scars', 'Erotic focus on scars.', '#EC4899', 1430),
    ('Size Kink / Size Difference', 'Erotic focus on body-size disparity between partners.', '#EC4899', 1440),
    ('Macrophilia', 'Attraction to giant beings.', '#EC4899', 1450),
    ('Microphilia', 'Attraction to tiny beings.', '#EC4899', 1460),
    ('Fingers in Mouth', 'Oral fixation involving fingers.', '#EC4899', 1470),
    ('Oral Fixation', 'General focus on mouth-centered stimulation.', '#EC4899', 1480),
    ('Scent Kink / Olfactophilia', 'Arousal from bodily or other smells.', '#EC4899', 1490),
    ('Bondage (Light)', 'Light physical restraint using scarves or soft rope.', '#EC4899', 1500),
    ('Bondage (Heavy)', 'Heavy or elaborate physical restraint.', '#EC4899', 1510),
    ('Rope Bondage', 'Restraint using rope.', '#EC4899', 1520),
    ('Shibari / Kinbaku', 'Japanese decorative rope bondage.', '#EC4899', 1530),
    ('Handcuffs', 'Restraint using handcuffs or cuffs.', '#EC4899', 1540),
    ('Harnesses', 'Worn restraint or decorative body harness.', '#EC4899', 1550),
    ('Spreader Bar', 'Rigid bar enforcing limb separation.', '#EC4899', 1560),
    ('Suspension', 'Being lifted or hung via bondage rigging.', '#EC4899', 1570),
    ('Wall / Cross Mounting', 'Restrained against a wall or St. Andrew''s cross.', '#EC4899', 1580),
    ('Stockades', 'Freestanding head-and-limb restraint device.', '#EC4899', 1590),
    ('Straightjackets', 'Garment-based full upper-body restraint.', '#EC4899', 1600),
    ('Cages', 'Enclosing restraint structure.', '#EC4899', 1610),
    ('Mummification', 'Full-body wrapping in plastic, bandage, or tape.', '#EC4899', 1620),
    ('Blindfolds', 'Sight deprivation during play.', '#EC4899', 1630),
    ('Hoods', 'Head covering, often with sensory-limiting function.', '#EC4899', 1640),
    ('Masks / Muzzles', 'Face covering or mouth restriction.', '#EC4899', 1650),
    ('Sensory Deprivation', 'Combined removal of sight, sound, and other senses.', '#EC4899', 1660),
    ('Ball / Bit Gag', 'Mouth gag in ball or bar style.', '#EC4899', 1670),
    ('Phallic Gag', 'Phallus-shaped mouth gag.', '#EC4899', 1680),
    ('Ring / Spider Gag', 'Ring gag that holds the mouth open.', '#EC4899', 1690),
    ('Tape Gag', 'Tape used to silence or restrict the mouth.', '#EC4899', 1700),
    ('Collar', 'Worn restraint signaling ownership or D/s dynamic.', '#EC4899', 1710),
    ('Collaring Ceremony', 'Ritual of placing a collar on a submissive.', '#EC4899', 1720),
    ('Leash', 'Tether attached to a collar.', '#EC4899', 1730),
    ('Chastity Devices', 'Devices preventing genital access or orgasm.', '#EC4899', 1740),
    ('Cock Rings', 'Rings worn at the base of the penis.', '#EC4899', 1750),
    ('Anal Hooks', 'Curved metal hooks used for anal restraint.', '#EC4899', 1760),
    ('Dominance / Submission (D/s)', 'Power-exchange dynamic between a dominant and submissive.', '#EC4899', 1770),
    ('Master / Slave (M/s)', 'Total power exchange dynamic.', '#EC4899', 1780),
    ('Slavery (Consensual Roleplay)', 'Roleplayed total ownership between consenting adults.', '#EC4899', 1790),
    ('Domestic Servitude', 'Submissive performs household tasks within a D/s frame.', '#EC4899', 1800),
    ('Discipline', 'Rules-and-punishment structure in power exchange.', '#EC4899', 1810),
    ('Punishment', 'Consequences imposed for rule infractions in D/s play.', '#EC4899', 1820),
    ('Brat Taming', 'Dynamic involving a defiant submissive being brought into line.', '#EC4899', 1830),
    ('Begging', 'Submissive verbally pleading for stimulation or release.', '#EC4899', 1840),
    ('Kneeling', 'Postural submission.', '#EC4899', 1850),
    ('Orgasm Control', 'Dominant controls if and when the submissive orgasms.', '#EC4899', 1860),
    ('Orgasm Denial', 'Withholding orgasm from the submissive.', '#EC4899', 1870),
    ('Forced Orgasm', 'Compelling orgasm against a submissive''s resistance in scene.', '#EC4899', 1880),
    ('Edging', 'Bringing close to orgasm then backing off, repeatedly.', '#EC4899', 1890),
    ('Overstimulation', 'Continuing stimulation past orgasm into oversensitivity.', '#EC4899', 1900),
    ('Multiple Orgasms', 'Sequential orgasms in a single session.', '#EC4899', 1910),
    ('Coming on Command', 'Orgasm triggered by a dominant''s verbal cue.', '#EC4899', 1920),
    ('Coming Untouched', 'Orgasm achieved without direct genital contact.', '#EC4899', 1930),
    ('Free Use', 'Submissive consents in advance to spontaneous use at any time.', '#EC4899', 1940),
    ('Consensual Non-Consent (CNC)', 'Roleplay simulating non-consent within prior negotiated agreement.', '#EC4899', 1950),
    ('Switching', 'Comfort filling both dominant and submissive roles.', '#EC4899', 1960),
    ('Safewords / Traffic Light System', 'Negotiated stop signals used in BDSM play.', '#EC4899', 1970),
    ('Kink Negotiation', 'Pre-scene consent and limits discussion.', '#EC4899', 1980),
    ('Bathroom Permission', 'Dominant controls submissive''s ability to use the bathroom.', '#EC4899', 1990),
    ('Pet Play (Soft)', 'Light roleplay as a pet — kitten, puppy, etc.', '#EC4899', 2000),
    ('Pet Play (Hard)', 'Immersive pet roleplay including handling and training.', '#EC4899', 2010),
    ('Puppy Play', 'Pet play where the submissive takes on a dog persona.', '#EC4899', 2020),
    ('Kitten Play', 'Pet play where the submissive takes on a cat persona.', '#EC4899', 2030),
    ('Pony Play', 'Pet play where the submissive takes on a horse persona.', '#EC4899', 2040),
    ('Furry / Anthropomorphic', 'Erotic interest in anthropomorphic animal characters.', '#EC4899', 2050),
    ('Human Furniture / Forniphilia', 'A person used as functional furniture.', '#EC4899', 2060),
    ('Slave Training', 'Structured submission and training arc in D/s.', '#EC4899', 2070),
    ('Interrogation', 'Roleplayed questioning under duress.', '#EC4899', 2080),
    ('Stuck & Fucked / Kabeshiri', 'Fantasy of being sexually used while stuck in a confined space.', '#EC4899', 2090),
    ('Teacher / Student', 'Roleplayed academic power dynamic.', '#EC4899', 2100),
    ('Doctor / Patient', 'Medical-themed roleplay.', '#EC4899', 2110),
    ('Medical Play', 'Use of medical instruments or settings in erotic scenes.', '#EC4899', 2120),
    ('Daddy Kink', 'Authority and caretaker roleplay with a paternal figure.', '#EC4899', 2130),
    ('Mommy Kink', 'Authority and caretaker roleplay with a maternal figure.', '#EC4899', 2140),
    ('DD/lg, MD/lb (Daddy/Mommy–Little)', 'Age-play-tinged power dynamic between caregiver and ''little''.', '#EC4899', 2150),
    ('Age Play', 'Adults roleplay acting younger or older than their actual age.', '#EC4899', 2160),
    ('Adult Baby / ABDL', 'Roleplay as an infant, often including diapers.', '#EC4899', 2170),
    ('Hunter / Prey', 'Pursuit and chase roleplay.', '#EC4899', 2180),
    ('Hypnosis / Hypnotism Kink', 'Erotic hypnosis or hypnotic suggestion play.', '#EC4899', 2190),
    ('Mind Control', 'Fantasy of controlling or having one''s will controlled.', '#EC4899', 2200),
    ('Mind Break', 'Fantasy of psychological collapse from extreme pleasure.', '#EC4899', 2210),
    ('Brainwashing', 'Reprogramming roleplay.', '#EC4899', 2220),
    ('Conditioning', 'Pavlovian-style arousal training roleplay.', '#EC4899', 2230),
    ('Sleep Play / Somnophilia (Consensual)', 'Sexual play while a consenting partner is asleep.', '#EC4899', 2240),
    ('Unaware / Free Use Fantasy', 'Fantasy where one party is unaware they are being used.', '#EC4899', 2250),
    ('Erotic Dancing / Strip Teasing', 'Performative sexual dance as foreplay or kink.', '#EC4899', 2260),
    ('Stripping / Disrobing', 'Removal of clothing as an erotic act.', '#EC4899', 2270),
    ('Lap Dances', 'Seated strip-tease performance.', '#EC4899', 2280),
    ('Sex Worker / Prostitution Roleplay', 'Roleplay of paid sex scenarios.', '#EC4899', 2290),
    ('Pornstar / Camstar Roleplay', 'Roleplay framed as performing on camera.', '#EC4899', 2300),
    ('Light Pain', 'Mild, contained pain stimuli in play.', '#EC4899', 2310),
    ('Heavy Pain', 'Intense pain stimuli in negotiated play.', '#EC4899', 2320),
    ('Spanking', 'Open-handed impact, usually on the buttocks.', '#EC4899', 2330),
    ('Body Slapping', 'Slapping non-genital body areas during play.', '#EC4899', 2340),
    ('Face Slapping', 'Slapping the face as part of negotiated play.', '#EC4899', 2350),
    ('Cock & Ball Torture (CBT)', 'Pain or restraint focused on male genitals.', '#EC4899', 2360),
    ('Pussy / Breast Torture', 'Pain or restraint focused on female anatomy.', '#EC4899', 2370),
    ('Caning', 'Striking with a cane.', '#EC4899', 2380),
    ('Flogging', 'Striking with a multi-tailed flogger.', '#EC4899', 2390),
    ('Whipping', 'Striking with a whip.', '#EC4899', 2400),
    ('Paddling', 'Striking with a paddle.', '#EC4899', 2410),
    ('Riding Crop', 'Striking with a riding crop.', '#EC4899', 2420),
    ('Hickies', 'Suction bruises left on the skin.', '#EC4899', 2430),
    ('Bruising', 'Intentional bruising during play.', '#EC4899', 2440),
    ('Branding', 'Application of burn marks as a mark of ownership or play.', '#EC4899', 2450),
    ('Cutting', 'Skin cutting in an edge play scene.', '#EC4899', 2460),
    ('Scratching', 'Scratching with nails during sex or play.', '#EC4899', 2470),
    ('Biting', 'Biting a partner during sex or play.', '#EC4899', 2480),
    ('Burning', 'Intentional burning as edge play.', '#EC4899', 2490),
    ('Hot Wax / Wax Play', 'Pouring controlled-temperature wax onto the body.', '#EC4899', 2500),
    ('Fire Play', 'Brief controlled flame stimulation.', '#EC4899', 2510),
    ('Knife Play', 'Use of blades for sensation or intimidation.', '#EC4899', 2520),
    ('Needle Play / Play Piercing', 'Temporary piercing with needles as sensation play.', '#EC4899', 2530),
    ('Electric Stimulation / Electro', 'Use of TENS units, violet wands, or similar devices.', '#EC4899', 2540),
    ('Nipple Clamps', 'Clamps applied to the nipples.', '#EC4899', 2550),
    ('Sounding', 'Urethral insertion of a medical sound for sensation.', '#EC4899', 2560),
    ('Figging', 'Inserting prepared ginger root for a burning sensation.', '#EC4899', 2570),
    ('Choking / Erotic Asphyxiation', 'Applying pressure to the neck or airway.', '#EC4899', 2580),
    ('Breath Play', 'Controlling or restricting a partner''s breathing.', '#EC4899', 2590),
    ('Tickling / Titillagnia', 'Erotic tickling, sometimes combined with restraint.', '#EC4899', 2600),
    ('Non-Con / Rape Play (Roleplay)', 'Consensually scripted simulation of non-consent.', '#EC4899', 2610),
    ('Coercion / Blackmail (Trope)', 'Sexualized coercion trope in fiction or roleplay.', '#EC4899', 2620),
    ('Drugging (Trope)', 'Roleplay or fiction involving being drugged.', '#EC4899', 2630),
    ('Forced Feeding', 'Force-feeding scenario in roleplay.', '#EC4899', 2640),
    ('Forced Masturbation', 'Compelled self-stimulation scenario.', '#EC4899', 2650),
    ('Forced Servitude', 'Coerced service scenario in fiction or roleplay.', '#EC4899', 2660),
    ('Sex Pollen / Fuck or Die', 'Fantasy device that compels sex for survival.', '#EC4899', 2670),
    ('Kidnapping / Abduction (Trope)', 'Abduction scenario in fiction or roleplay.', '#EC4899', 2680),
    ('Power Imbalance', 'Erotic focus on uneven power dynamics between partners.', '#EC4899', 2690),
    ('Dehumanization', 'Treating a partner as a non-person in scene.', '#EC4899', 2700),
    ('Humiliation (Private)', 'Verbal or situational humiliation in private.', '#EC4899', 2710),
    ('Humiliation (Public)', 'Humiliation in public or with an audience.', '#EC4899', 2720),
    ('Degradation', 'Verbal or situational degradation during play.', '#EC4899', 2730),
    ('Verbal Abuse (In Scene)', 'Negotiated use of insults or slurs as part of play.', '#EC4899', 2740),
    ('Praise Kink', 'Arousal from receiving verbal praise or being called good.', '#EC4899', 2750),
    ('Dirty Talk', 'Sexually explicit verbal exchange during sex.', '#EC4899', 2760),
    ('Objectification', 'Treating a partner as a sexual object.', '#EC4899', 2770),
    ('Claiming / Marking', 'Symbolic possession through bite marks, hickies, etc.', '#EC4899', 2780),
    ('Possessive Behavior', 'Jealousy or ownership framing within a relationship.', '#EC4899', 2790),
    ('Jealousy (Kink)', 'Erotic enjoyment derived from jealousy.', '#EC4899', 2800),
    ('Competence Kink', 'Arousal from a partner''s displayed skill or competence.', '#EC4899', 2810),
    ('Tentacles', 'Fantasy involving tentacled creatures.', '#EC4899', 2820),
    ('Monster / Beast', 'Fantasy involving monsters or beast-like creatures.', '#EC4899', 2830),
    ('Alien Fantasy', 'Fantasy involving extraterrestrial beings.', '#EC4899', 2840),
    ('Xenophilia', 'Attraction to non-human entities.', '#EC4899', 2850),
    ('Futanari / Dickgirl', 'Fictional female characters depicted with male genitalia.', '#EC4899', 2860),
    ('Transformation', 'Fantasy of a body changing form.', '#EC4899', 2870),
    ('Body Swap', 'Fantasy of switching bodies with another person.', '#EC4899', 2880),
    ('Gender Swap', 'Fantasy of changing one''s gender.', '#EC4899', 2890),
    ('Knotting', 'Canid or werewolf trope involving an inflating knot during sex.', '#EC4899', 2900),
    ('Alpha/Beta/Omega (Omegaverse)', 'Fanfic universe with biological hierarchy and heat cycles.', '#EC4899', 2910),
    ('Animal-Human Hybrids', 'Anthropomorphic hybrid characters.', '#EC4899', 2920),
    ('Vampires', 'Vampire-themed sexual fantasy.', '#EC4899', 2930),
    ('Werewolves', 'Werewolf-themed sexual fantasy.', '#EC4899', 2940),
    ('Telepathic / Empathic Bonds', 'Mind-linked partners sharing sensations.', '#EC4899', 2950),
    ('Selfcest', 'Sexual interest in alternate or clone versions of oneself.', '#EC4899', 2960),
    ('Acrotomophilia', 'Attraction to amputees.', '#EC4899', 2970),
    ('Apotemnophilia', 'Desire to be an amputee.', '#EC4899', 2980),
    ('Nullification / Castration Kink', 'Genital removal fantasy.', '#EC4899', 2990),
    ('Vore', 'Fantasy of being eaten or swallowing someone whole.', '#EC4899', 3000),
    ('Cannibalism (Fictional)', 'Story-level cannibalism trope.', '#EC4899', 3010),
    ('Snuff / Murder Kink', 'Story-level lethal scenario.', '#EC4899', 3020),
    ('Fear Play', 'Arousal from inducing or experiencing fear.', '#EC4899', 3030),
    ('Incest (Consensual Adult Roleplay)', 'Roleplayed kinship dynamic between consenting adults.', '#EC4899', 3040),
    ('Pseudo-Incest / Step-Family', 'Fictional non-blood kinship dynamic.', '#EC4899', 3050),
    ('Cheating / Infidelity (Trope)', 'Adultery trope in fiction or fantasy.', '#EC4899', 3060),
    ('Sensation Play', 'Variety of tactile stimuli used for erotic effect.', '#EC4899', 3070),
    ('Temperature Play', 'Use of hot and cold stimulation.', '#EC4899', 3080),
    ('Wet & Messy / WAM', 'Arousal from substances (food, slime, etc.) on the body.', '#EC4899', 3090),
    ('Food Play / Sitophilia', 'Sexual use of food.', '#EC4899', 3100),
    ('Sploshing', 'WAM variant with messy substances poured over the body.', '#EC4899', 3110),
    ('Massages', 'Erotic massage.', '#EC4899', 3120),
    ('Bathing / Washing', 'Bathing or washing a partner as an erotic act.', '#EC4899', 3130),
    ('Licking', 'Licking a partner''s body for arousal.', '#EC4899', 3140),
    ('Teasing', 'Prolonged anticipation and denial of stimulation.', '#EC4899', 3150),
    ('Age Difference / Age Gap', 'Erotic focus on age disparity between partners.', '#EC4899', 3160),
    ('Drug Use (In Scene / Fiction)', 'Drugs incorporated into sex or roleplay.', '#EC4899', 3170),
    ('Smoking / Capnolagnia', 'Arousal involving smoking.', '#EC4899', 3180),
    ('Shotgunning', 'Sharing smoke mouth-to-mouth.', '#EC4899', 3190),
    ('Exhaustion / Fucked-Out', 'Arousal from a sexually exhausted or well-used partner.', '#EC4899', 3200),
    ('First Time', 'Erotic focus on a first sexual encounter with a specific partner.', '#EC4899', 3210),
    ('Virginity', 'Erotic focus on virginity or its loss.', '#EC4899', 3220),
    ('Sexual Inexperience', 'Naive or innocent partner trope.', '#EC4899', 3230),
    ('Promiscuity', 'Erotic focus on a highly sexually active partner.', '#EC4899', 3240),
    ('Fighting / Wrestling', 'Combative or sporty erotic framing.', '#EC4899', 3250),
    ('Sex Tapes', 'Recording sex; arousal from being recorded.', '#EC4899', 3260),
    ('Watching Porn', 'Porn-watching incorporated as part of sex.', '#EC4899', 3270),
    ('Sugar Daddy / Sugar Baby', 'Transactional age-gap dynamic.', '#EC4899', 3280),
    ('Sloppy Seconds', 'Sex with a partner immediately after another person.', '#EC4899', 3290),
    ('Oviposition', 'Fantasy of egg-laying.', '#EC4899', 3300),
    ('Hurt / Comfort', 'Story arc focused on injury followed by consolation.', '#EC4899', 3310),
    ('Friends to Lovers', 'Relationship arc where friends become romantic partners.', '#EC4899', 3320),
    ('Enemies to Lovers', 'Relationship arc where antagonists become lovers.', '#EC4899', 3330),
    ('Friends with Benefits', 'Casual sexual friendship without committed relationship.', '#EC4899', 3340),
    ('Fake / Pretend Relationship', 'Couple pretends to be together, often developing real feelings.', '#EC4899', 3350),
    ('Only One Bed', 'Forced-proximity trope involving shared sleeping arrangements.', '#EC4899', 3360),
    ('Pining (Mutual / Unrequited)', 'Romantic longing arc, one-sided or mutual.', '#EC4899', 3370),
    ('Unresolved Sexual Tension (UST)', 'Sustained sexual tension without resolution.', '#EC4899', 3380),
    ('Established Relationship', 'Story begins with the couple already together.', '#EC4899', 3390),
    ('Domestic Fluff', 'Cohabitation and everyday domestic scenes as erotic or intimate content.', '#EC4899', 3400),
    ('Soulmates / Soulmate Marks', 'Predestined partner trope, sometimes with a visible identifying mark.', '#EC4899', 3410),
    ('Amnesia', 'Memory-loss trope affecting relationship or identity.', '#EC4899', 3420),
    ('Love Triangles', 'Three-way romantic tension trope.', '#EC4899', 3430),
    ('Reader Insert', 'Fiction where the reader is cast as a character.', '#EC4899', 3440),
    ('Royalty AU', 'Royal or noble setting alternate universe.', '#EC4899', 3450),
    ('Historical AU', 'Period or historical setting alternate universe.', '#EC4899', 3460),
    ('College / High School AU', 'Academic setting alternate universe.', '#EC4899', 3470),
    ('Coffee Shop AU', 'Mundane modern setting alternate universe.', '#EC4899', 3480),
    ('Dystopian / Fantasy / Supernatural AU', 'Alternate universe with speculative or supernatural setting.', '#EC4899', 3490);
