import Foundation
import AppKit

/// Producer / AE deliverable export. Two formats:
///
/// - **CSV** — every asset row with technical metadata + Kyno-parity
///   log fields. Importable into Excel, Numbers, Google Sheets.
///   Fast; no thumbnails (CSV can't embed images).
/// - **HTML** — same columns plus a thumbnail column at the front,
///   each cell carrying a base64-embedded PNG so the resulting file
///   is self-contained and shareable as a single attachment.
///   Slower (one extract per asset) but the canonical producer
///   deliverable when thumbnails matter.
///
/// Reads everything off the in-memory AppState caches
/// (`clipMetadataIndex`, `tagIndex`, `ratingIndex`) so the export
/// doesn't bounce off SQLite per row.
@MainActor
enum ReportExporter {
    /// Format the timestamp portion of a default report filename.
    static func filenameTimestamp() -> String {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd_HHmmss"
        return f.string(from: Date())
    }

    /// Emit CSV to `destination`. Writes a header row first; rows are
    /// quote-escaped where any field contains comma / quote / newline.
    static func writeCSV(assets: [Asset], to destination: URL,
                          appState: AppState) throws {
        var lines: [String] = []
        lines.append(csvHeader)
        for asset in assets {
            lines.append(csvRow(for: asset, appState: appState))
        }
        let body = lines.joined(separator: "\r\n") + "\r\n"
        try body.write(to: destination, atomically: true, encoding: .utf8)
    }

    /// Emit a self-contained HTML report. Thumbnails are generated on
    /// the fly (delegated to `ThumbnailService`) and embedded as
    /// base64 PNG. Pure synchronous because the call sites we have
    /// today drive < 1000 assets — async + progress is the next-step
    /// improvement. Returns `(written, skipped)` so the UI can flash
    /// a status.
    static func writeHTML(assets: [Asset], to destination: URL,
                           appState: AppState) async throws -> (written: Int, skipped: Int) {
        var rows: [String] = []
        var written = 0
        var skipped = 0
        for asset in assets {
            // One frame per asset — the middle of the strip — embedded
            // as a base64 PNG. Falls back to a placeholder cell when
            // ThumbnailService returns nothing (image-only asset
            // without a thumbnail extraction path, broken file, etc.).
            let strip = await ThumbnailService.thumbnails(for: asset, count: 1)
            var thumbHTML: String
            if let url = strip.first,
               let data = try? Data(contentsOf: url) {
                let b64 = data.base64EncodedString()
                thumbHTML = "<img src=\"data:image/jpeg;base64,\(b64)\" />"
                written += 1
            } else {
                thumbHTML = "<span class=\"missing\">no preview</span>"
                skipped += 1
            }
            rows.append(htmlRow(thumbCell: thumbHTML, asset: asset,
                                 appState: appState))
        }
        let body = """
        <!doctype html>
        <html lang="en">
        <head>
        <meta charset="utf-8">
        <title>PurpleReel media report</title>
        <style>
            body { font: 13px -apple-system, BlinkMacSystemFont, sans-serif; color: #222; margin: 0; padding: 24px; }
            h1   { font-size: 18px; margin: 0 0 12px; }
            .meta { color: #666; margin-bottom: 18px; font-size: 12px; }
            table { border-collapse: collapse; width: 100%; }
            th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; vertical-align: top; }
            th { background: #f3f3f3; font-weight: 600; }
            td.thumb { width: 132px; }
            td.thumb img { width: 120px; height: auto; display: block; border-radius: 4px; }
            td.thumb .missing { color: #999; font-style: italic; font-size: 11px; }
            tr:nth-child(even) td { background: #fafafa; }
            .num { font-variant-numeric: tabular-nums; }
        </style>
        </head>
        <body>
        <h1>Media report</h1>
        <div class="meta">Generated by PurpleReel · \(htmlEscape(Self.filenameTimestamp())) · \(assets.count) clip(s)</div>
        <table>
        <thead>
        \(htmlHeader)
        </thead>
        <tbody>
        \(rows.joined(separator: "\n"))
        </tbody>
        </table>
        </body>
        </html>
        """
        try body.write(to: destination, atomically: true, encoding: .utf8)
        return (written, skipped)
    }

    // MARK: - CSV row construction

    /// Header row, computed once per export. A computed property
    /// instead of a `static let` because the type-checker chokes
    /// on a 22-element literal that immediately `.map`s + `.join`s.
    private static var csvHeader: String {
        var cols: [String] = []
        cols.append("Filename")
        cols.append("Codec")
        cols.append("Resolution")
        cols.append("Display Size")
        cols.append("Aspect Ratio")
        cols.append("FPS")
        cols.append("Duration (sec)")
        cols.append("Size (bytes)")
        cols.append("Date Modified")
        cols.append("Date Created")
        cols.append("Date Recorded")
        cols.append("Rating")
        cols.append("Title")
        cols.append("Description")
        cols.append("Reel")
        cols.append("Scene")
        cols.append("Shot")
        cols.append("Take")
        cols.append("Angle")
        cols.append("Camera")
        cols.append("Audio Channels")
        cols.append("Tags")
        return cols.map(csvEscape).joined(separator: ",")
    }

    private static func csvRow(for asset: Asset, appState: AppState) -> String {
        // Built piecemeal because a 22-element array literal with
        // mixed transforms blows Swift's type-checker budget.
        let meta = asset.rowId.flatMap { appState.clipMetadataIndex[$0] }
        let tags = appState.tagIndex[asset.path]?.sorted()
            .joined(separator: "; ") ?? ""
        let rating = appState.ratingIndex[asset.path].map(String.init) ?? ""
        let duration = asset.durationSeconds.map { String(format: "%.3f", $0) } ?? ""
        let createdStr = asset.createdAt.map(dateString) ?? ""
        let recordedStr = asset.recordedAt.map(dateString) ?? ""
        var cells: [String] = []
        cells.append(asset.filename)
        cells.append(asset.codec ?? "")
        cells.append(resolutionString(asset))
        cells.append(displaySizeString(asset))
        cells.append(aspectRatioString(asset))
        cells.append(fpsString(asset))
        cells.append(duration)
        cells.append("\(asset.sizeBytes)")
        cells.append(dateString(asset.modifiedAt))
        cells.append(createdStr)
        cells.append(recordedStr)
        cells.append(rating)
        cells.append(meta?.title ?? "")
        cells.append(meta?.description ?? "")
        cells.append(meta?.reel ?? "")
        cells.append(meta?.scene ?? "")
        cells.append(meta?.shot ?? "")
        cells.append(meta?.take ?? "")
        cells.append(meta?.angle ?? "")
        cells.append(meta?.camera ?? "")
        cells.append(meta?.audioChannelNames ?? "")
        cells.append(tags)
        return cells.map(csvEscape).joined(separator: ",")
    }

    /// Quote-and-escape a CSV cell per RFC 4180: only quote if the
    /// cell contains a comma, double quote, CR, or LF.
    private static func csvEscape(_ raw: String) -> String {
        if raw.contains(",") || raw.contains("\"")
            || raw.contains("\n") || raw.contains("\r") {
            let escaped = raw.replacingOccurrences(of: "\"", with: "\"\"")
            return "\"\(escaped)\""
        }
        return raw
    }

    // MARK: - HTML row construction

    private static let htmlHeader = """
    <tr>
      <th>Thumbnail</th>
      <th>Filename</th>
      <th>Codec</th>
      <th>Resolution</th>
      <th>Display Size</th>
      <th>Aspect Ratio</th>
      <th>FPS</th>
      <th>Duration</th>
      <th>Size</th>
      <th>Date Modified</th>
      <th>Date Created</th>
      <th>Date Recorded</th>
      <th>Rating</th>
      <th>Title</th>
      <th>Description</th>
      <th>Reel</th>
      <th>Scene</th>
      <th>Shot</th>
      <th>Take</th>
      <th>Angle</th>
      <th>Camera</th>
      <th>Audio Channels</th>
      <th>Tags</th>
    </tr>
    """

    private static func htmlRow(thumbCell: String,
                                 asset: Asset,
                                 appState: AppState) -> String {
        // Same type-check rationale as `csvRow`: build the cells
        // imperatively so Swift doesn't choke on a 22-arg literal
        // with mixed `??` + function-call subexpressions.
        let meta = asset.rowId.flatMap { appState.clipMetadataIndex[$0] }
        let tags = appState.tagIndex[asset.path]?.sorted()
            .joined(separator: ", ") ?? ""
        // `stars = -1` means Rejected (Kyno-parity, C7); render as
        // an explicit label so the HTML report carries the intent.
        // Anything else is a non-negative star count.
        let rating: String = {
            guard let s = appState.ratingIndex[asset.path] else { return "" }
            if s < 0 { return "Rejected" }
            return String(repeating: "★", count: s)
        }()
        let duration = asset.durationSeconds.map(formatDuration) ?? "—"
        let createdStr = asset.createdAt.map(dateString) ?? "—"
        let recordedStr = asset.recordedAt.map(dateString) ?? "—"
        var cells: [String] = []
        cells.append(htmlEscape(asset.filename))
        cells.append(htmlEscape(asset.codec ?? "—"))
        cells.append(htmlEscape(resolutionString(asset)))
        cells.append(htmlEscape(displaySizeString(asset)))
        cells.append(htmlEscape(aspectRatioString(asset)))
        cells.append(htmlEscape(fpsString(asset)))
        cells.append(htmlEscape(duration))
        cells.append(htmlEscape(formatBytes(asset.sizeBytes)))
        cells.append(htmlEscape(dateString(asset.modifiedAt)))
        cells.append(htmlEscape(createdStr))
        cells.append(htmlEscape(recordedStr))
        cells.append(htmlEscape(rating.isEmpty ? "—" : rating))
        cells.append(htmlEscape(meta?.title ?? "—"))
        cells.append(htmlEscape(meta?.description ?? "—"))
        cells.append(htmlEscape(meta?.reel ?? "—"))
        cells.append(htmlEscape(meta?.scene ?? "—"))
        cells.append(htmlEscape(meta?.shot ?? "—"))
        cells.append(htmlEscape(meta?.take ?? "—"))
        cells.append(htmlEscape(meta?.angle ?? "—"))
        cells.append(htmlEscape(meta?.camera ?? "—"))
        cells.append(htmlEscape(meta?.audioChannelNames ?? "—"))
        cells.append(htmlEscape(tags.isEmpty ? "—" : tags))
        let tds = cells.map { "<td>\($0)</td>" }.joined()
        return "<tr><td class=\"thumb\">\(thumbCell)</td>\(tds)</tr>"
    }

    /// Escape minimal HTML — `& < > "` is enough for our cell text
    /// because we never emit user content inside HTML attribute
    /// values except for the base64 thumbnails (which are pure
    /// alnum + `=` + `/` + `+`).
    private static func htmlEscape(_ raw: String) -> String {
        raw.replacingOccurrences(of: "&", with: "&amp;")
           .replacingOccurrences(of: "<", with: "&lt;")
           .replacingOccurrences(of: ">", with: "&gt;")
           .replacingOccurrences(of: "\"", with: "&quot;")
    }

    // MARK: - Cell formatters

    private static func resolutionString(_ a: Asset) -> String {
        guard let w = a.widthPx, let h = a.heightPx else { return "" }
        return "\(w) × \(h)"
    }

    /// Short-edge → 8K / 4K / QHD / 1080p / 720p / SD. Matches the
    /// "Display Size" list-view column the user can toggle.
    private static func displaySizeString(_ a: Asset) -> String {
        guard let w = a.widthPx, let h = a.heightPx, w > 0, h > 0
        else { return "" }
        let short = min(w, h)
        switch short {
        case 4320...:        return "8K"
        case 2160..<4320:    return "4K"
        case 1440..<2160:    return "QHD"
        case 1080..<1440:    return "1080p"
        case 720..<1080:     return "720p"
        case 576..<720:      return "576p"
        case 480..<576:      return "480p"
        default:             return "SD"
        }
    }

    private static func aspectRatioString(_ a: Asset) -> String {
        guard let w = a.widthPx, let h = a.heightPx, w > 0, h > 0
        else { return "" }
        let ratio = Double(w) / Double(h)
        let canon: [(Double, String)] = [
            (16.0/9, "16:9"), (4.0/3, "4:3"), (1.85, "1.85:1"),
            (2.35, "2.35:1"), (2.39, "2.39:1"), (1.0, "1:1"),
            (9.0/16, "9:16"), (3.0/4, "3:4"),
        ]
        for (target, label) in canon where abs(ratio - target) < 0.02 {
            return label
        }
        return String(format: "%.2f:1", ratio)
    }

    private static func fpsString(_ a: Asset) -> String {
        guard let f = a.frameRate, f > 0 else { return "" }
        return String(format: "%.2f", f)
    }

    private static func formatDuration(_ secs: Double) -> String {
        guard secs.isFinite, secs >= 0 else { return "—" }
        let total = Int(secs.rounded())
        let h = total / 3600
        let m = (total / 60) % 60
        let s = total % 60
        return h > 0
            ? String(format: "%d:%02d:%02d", h, m, s)
            : String(format: "%d:%02d", m, s)
    }

    private static func formatBytes(_ b: Int64) -> String {
        let f = ByteCountFormatter()
        f.allowedUnits = [.useMB, .useGB, .useTB]
        f.countStyle = .file
        return f.string(fromByteCount: b)
    }

    private static func dateString(_ d: Date) -> String {
        let f = DateFormatter()
        f.dateStyle = .medium
        f.timeStyle = .short
        return f.string(from: d)
    }
}
