// Turns the built Spin-the-Wheel player (dist-wheel/index.html) into a TS module the
// creator can import as a string. The creator injects the wheel payload into this
// template at deploy time, in the browser, to produce a self-contained wheel file.
//
// Run automatically by `npm run build` (between build:wheel and build:creator).

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const src = resolve(root, 'dist-wheel/index.html');
const out = resolve(root, 'src/creator/generated/wheelTemplate.ts');

if (!existsSync(src)) {
  console.error(`[embed-wheel] missing ${src} — run "npm run build:wheel" first.`);
  process.exit(1);
}

const html = readFileSync(src, 'utf8');
if (!html.includes('<!--QUIZ_PAYLOAD-->')) {
  console.error('[embed-wheel] wheel HTML is missing the <!--QUIZ_PAYLOAD--> marker.');
  process.exit(1);
}

// Escape for embedding inside a normal template literal.
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const banner = '// AUTO-GENERATED by scripts/embed-wheel.mjs — do not edit by hand.\n' +
  '// Source: dist-wheel/index.html (the built Spin-the-Wheel single-file bundle).\n' +
  '/* eslint-disable */\n';

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${banner}export const WHEEL_TEMPLATE = \`${escaped}\`;\n`, 'utf8');

console.log(`[embed-wheel] wrote ${out} (${(html.length / 1024).toFixed(0)} KB).`);
