// Restore BOTH committed player-template stubs to their tiny canonical form.
//
// `npm run build` overwrites src/creator/generated/{player,wheel}Template.ts locally
// with the ~900 KB built bundles. Those blobs must NEVER be committed — they bloat
// the repo and are fully regenerated by the build. Run `npm run restore:stubs`
// before committing (and `npm run check:stubs` / tests/stubs.test.ts guards it).

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const gen = resolve(__dirname, '..', 'src/creator/generated');

const STUBS = {
  'playerTemplate.ts': {
    banner:
      '// COMMITTED STUB — replaced at build time by scripts/embed-player.mjs with the real\n' +
      '// built Player HTML. This stub only exists so `vite dev` and `tsc` resolve on a\n' +
      '// fresh checkout; `npm run build` always regenerates it from dist-player/index.html.\n',
    name: 'PLAYER_TEMPLATE',
    body: 'Run "npm run build" to embed the real player.',
  },
  'wheelTemplate.ts': {
    banner:
      '// COMMITTED STUB — replaced at build time by scripts/embed-wheel.mjs with the real\n' +
      '// built Spin-the-Wheel player HTML. This stub only exists so `vite dev` and `tsc`\n' +
      '// resolve on a fresh checkout; `npm run build` always regenerates it from\n' +
      '// dist-wheel/index.html. Restore this stub (npm run restore:stubs) before committing.\n',
    name: 'WHEEL_TEMPLATE',
    body: 'Run "npm run build" to embed the real wheel.',
  },
};

for (const [file, { banner, name, body }] of Object.entries(STUBS)) {
  const html = `<!doctype html><html><head><meta charset="UTF-8"><!--QUIZ_PAYLOAD--></head><body><div id="root">${body}</div></body></html>`;
  const contents = `${banner}/* eslint-disable */\nexport const ${name} = \`${html}\`;\n`;
  writeFileSync(resolve(gen, file), contents, 'utf8');
  console.log(`[restore-stubs] restored ${file} (${contents.length} bytes).`);
}
