// AUTO-GENERATED by scripts/build-data.mjs from scripts/world.source.json — DO NOT EDIT.
// 100 land provinces registered to the photographed History of the World board
// (the scan is the basemap; each (x,y) is a fraction of it). Names, positions,
// adjacency, areas and empire homelands are derived game data (facts); retune by
// editing world.source.json + coords.json and re-running the generator.

import type { AreaDef, Land, LandId, MapData, SeaId } from '../types'
import { AREA_NAMES, valueByEpoch } from './areaValues'

export const WORLD_SEAS: SeaId[] = ["adriatic_sea","aegean_sea","arabian_sea","arctic_ocean","atlantic","baltic","bay_of_bengal","bering_sea","black_sea","caribbean","caspian_sea","celebes_sea","coral_sea","east_china_sea","gulf_of_guinea","gulf_of_mexico","indian_ocean","java_sea","mediterranean","mozambique_channel","north_sea","pacific","persian_gulf","red_sea","sea_of_japan","south_china_sea","southern_ocean","tasman_sea","yellow_sea"]

export const WORLD_LANDS: Land[] = [
  { id: "caucasus", name: "Caucasus", area: "middle_east", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.44, y: 0.558, borders: ["danube","dnieper","eastern_anatolia","persian_plateau","turanian_plain","western_anatolia","western_steppe"], seaBorders: [] },
  { id: "western_anatolia", name: "Western Anatolia", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.371, y: 0.617, borders: ["balkans","caucasus","crete","danube","eastern_anatolia","levant","morea"], seaBorders: [] },
  { id: "eastern_anatolia", name: "Eastern Anatolia", area: "middle_east", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.435, y: 0.615, borders: ["caucasus","levant","persian_plateau","western_anatolia","zagros"], seaBorders: [] },
  { id: "persian_plateau", name: "Persian Plateau", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.524, y: 0.611, borders: ["caucasus","eastern_anatolia","hindu_kush","persian_salt_desert","turanian_plain","upper_indus","zagros"], seaBorders: [] },
  { id: "levant", name: "Levant", area: "middle_east", barren: false, difficultTerrain: [], hasResource: true, x: 0.4, y: 0.679, borders: ["crete","eastern_anatolia","palestine","upper_tigris","western_anatolia","zagros"], seaBorders: [] },
  { id: "zagros", name: "Zagros", area: "middle_east", barren: false, difficultTerrain: ["mountain"], hasResource: true, x: 0.468, y: 0.675, borders: ["eastern_anatolia","levant","middle_tigris","persian_plateau","persian_salt_desert","upper_tigris"], seaBorders: [] },
  { id: "upper_tigris", name: "Upper Tigris", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.423, y: 0.704, borders: ["levant","middle_tigris","palestine","zagros"], seaBorders: [] },
  { id: "persian_salt_desert", name: "Persian Salt Desert", area: "middle_east", barren: true, difficultTerrain: [], hasResource: false, x: 0.528, y: 0.694, borders: ["lower_indus","lower_tigris","middle_tigris","persian_plateau","upper_indus","zagros"], seaBorders: [] },
  { id: "palestine", name: "Palestine", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.346, y: 0.75, borders: ["crete","levant","lower_tigris","middle_tigris","nile_delta","nubia","syrian_desert","upper_tigris"], seaBorders: [] },
  { id: "middle_tigris", name: "Middle Tigris", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.43, y: 0.745, borders: ["lower_tigris","palestine","persian_salt_desert","upper_tigris","zagros"], seaBorders: [] },
  { id: "lower_tigris", name: "Lower Tigris", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.431, y: 0.78, borders: ["arabian_peninsula","middle_tigris","palestine","persian_salt_desert","syrian_desert"], seaBorders: [] },
  { id: "syrian_desert", name: "Syrian Desert", area: "middle_east", barren: true, difficultTerrain: [], hasResource: false, x: 0.385, y: 0.824, borders: ["arabian_peninsula","lower_tigris","palestine","upper_nile"], seaBorders: [] },
  { id: "arabian_peninsula", name: "Arabian Peninsula", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.364, y: 0.877, borders: ["lower_tigris","syrian_desert","upper_nile"], seaBorders: [] },
  { id: "libya", name: "Libya", area: "north_africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.22, y: 0.724, borders: ["central_africa","nile_delta","nubia","sahara_desert","sierra_morena"], seaBorders: [] },
  { id: "sahara_desert", name: "Sahara Desert", area: "north_africa", barren: true, difficultTerrain: [], hasResource: false, x: 0.156, y: 0.728, borders: ["central_africa","gold_coast","libya","sierra_morena"], seaBorders: [] },
  { id: "nile_delta", name: "Nile Delta", area: "north_africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.281, y: 0.756, borders: ["crete","libya","nubia","palestine"], seaBorders: [] },
  { id: "nubia", name: "Nubia", area: "north_africa", barren: false, difficultTerrain: [], hasResource: true, x: 0.265, y: 0.825, borders: ["central_africa","libya","nile_delta","palestine","upper_nile"], seaBorders: [] },
  { id: "upper_nile", name: "Upper Nile", area: "north_africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.274, y: 0.857, borders: ["arabian_peninsula","central_africa","nubia","syrian_desert"], seaBorders: [] },
  { id: "gold_coast", name: "Gold Coast", area: "africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.103, y: 0.722, borders: ["central_africa","congo_basin","sahara_desert","sierra_morena"], seaBorders: [] },
  { id: "central_africa", name: "Central Africa", area: "africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.163, y: 0.815, borders: ["congo_basin","east_africa","gold_coast","libya","nubia","sahara_desert","upper_nile"], seaBorders: [] },
  { id: "congo_basin", name: "Congo Basin", area: "africa", barren: false, difficultTerrain: ["forest"], hasResource: true, x: 0.098, y: 0.825, borders: ["central_africa","east_africa","gold_coast","southern_africa"], seaBorders: [] },
  { id: "southern_africa", name: "Southern Africa", area: "africa", barren: false, difficultTerrain: ["forest"], hasResource: true, x: 0.06, y: 0.945, borders: ["congo_basin","east_africa","madagascar"], seaBorders: [] },
  { id: "east_africa", name: "East Africa", area: "africa", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.144, y: 0.895, borders: ["central_africa","congo_basin","madagascar","southern_africa"], seaBorders: [] },
  { id: "madagascar", name: "Madagascar", area: "africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.171, y: 0.938, borders: ["east_africa","southern_africa"], seaBorders: [] },
  { id: "great_plain_of_china", name: "Great Plain of China", area: "china", barren: false, difficultTerrain: [], hasResource: false, x: 0.758, y: 0.254, borders: ["chekiang","korea","yangtze_kiang","yellow_river"], seaBorders: [] },
  { id: "manchuria", name: "Manchuria", area: "china", barren: false, difficultTerrain: [], hasResource: false, x: 0.674, y: 0.135, borders: ["hokkaido","korea"], seaBorders: [] },
  { id: "yellow_river", name: "Yellow River", area: "china", barren: false, difficultTerrain: [], hasResource: false, x: 0.73, y: 0.26, borders: ["great_plain_of_china","korea","mongolia","wei_river","yangtze_kiang"], seaBorders: [] },
  { id: "chekiang", name: "Chekiang", area: "china", barren: false, difficultTerrain: ["forest"], hasResource: true, x: 0.786, y: 0.351, borders: ["great_plain_of_china","si_kiang","yangtze_kiang"], seaBorders: [] },
  { id: "wei_river", name: "Wei River", area: "china", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.705, y: 0.345, borders: ["eastern_steppe","mongolia","szechwan","yangtze_kiang","yellow_river"], seaBorders: [] },
  { id: "yangtze_kiang", name: "Yangtze Kiang", area: "china", barren: false, difficultTerrain: [], hasResource: false, x: 0.745, y: 0.35, borders: ["chekiang","great_plain_of_china","si_kiang","szechwan","wei_river","yellow_river"], seaBorders: [] },
  { id: "si_kiang", name: "Si-Kiang", area: "china", barren: false, difficultTerrain: [], hasResource: false, x: 0.76, y: 0.419, borders: ["chekiang","mekong","szechwan","yangtze_kiang"], seaBorders: [] },
  { id: "szechwan", name: "Szechwan", area: "china", barren: false, difficultTerrain: [], hasResource: false, x: 0.717, y: 0.44, borders: ["eastern_steppe","irrawaddy","mekong","plateau_of_tibet","si_kiang","wei_river","yangtze_kiang"], seaBorders: [] },
  { id: "ganges_delta", name: "Ganges Delta", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.691, y: 0.571, borders: ["eastern_deccan","ganges_valley","irrawaddy","malayan_peninsula","plateau_of_tibet"], seaBorders: [] },
  { id: "hindu_kush", name: "Hindu Kush", area: "india", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.557, y: 0.596, borders: ["ganges_valley","persian_plateau","turanian_plain","upper_indus"], seaBorders: [] },
  { id: "ganges_valley", name: "Ganges Valley", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.647, y: 0.58, borders: ["eastern_deccan","ganges_delta","hindu_kush","plateau_of_tibet","upper_indus"], seaBorders: [] },
  { id: "upper_indus", name: "Upper Indus", area: "india", barren: false, difficultTerrain: [], hasResource: true, x: 0.593, y: 0.627, borders: ["eastern_deccan","ganges_valley","hindu_kush","lower_indus","persian_plateau","persian_salt_desert","western_deccan"], seaBorders: [] },
  { id: "eastern_deccan", name: "Eastern Deccan", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.678, y: 0.659, borders: ["eastern_ghats","ganges_delta","ganges_valley","malayan_peninsula","upper_indus","western_deccan"], seaBorders: [] },
  { id: "lower_indus", name: "Lower Indus", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.584, y: 0.702, borders: ["persian_salt_desert","upper_indus","western_deccan","western_ghats"], seaBorders: [] },
  { id: "western_deccan", name: "Western Deccan", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.634, y: 0.716, borders: ["eastern_deccan","eastern_ghats","lower_indus","upper_indus","western_ghats"], seaBorders: [] },
  { id: "eastern_ghats", name: "Eastern Ghats", area: "india", barren: false, difficultTerrain: ["mountain"], hasResource: true, x: 0.675, y: 0.764, borders: ["ceylon","eastern_deccan","western_deccan","western_ghats"], seaBorders: [] },
  { id: "western_ghats", name: "Western Ghats", area: "india", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.637, y: 0.754, borders: ["ceylon","eastern_ghats","lower_indus","western_deccan"], seaBorders: [] },
  { id: "ceylon", name: "Ceylon", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.695, y: 0.81, borders: ["eastern_ghats","sumatra","the_outback","western_ghats"], seaBorders: [] },
  { id: "central_massif", name: "Central Massif", area: "southern_europe", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.226, y: 0.494, borders: ["alps","northern_apennines","pyrenees","southern_iberia","western_gaul"], seaBorders: [] },
  { id: "pyrenees", name: "Pyrenees", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.176, y: 0.493, borders: ["central_massif","southern_iberia","western_gaul","western_iberia"], seaBorders: [] },
  { id: "alps", name: "Alps", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.269, y: 0.492, borders: ["central_europe","central_massif","dalmatia","lower_rhine","northern_apennines","northern_gaul","western_gaul"], seaBorders: [] },
  { id: "western_iberia", name: "Western Iberia", area: "southern_europe", barren: false, difficultTerrain: [], hasResource: true, x: 0.141, y: 0.515, borders: ["pyrenees","sierra_morena","southern_iberia"], seaBorders: [] },
  { id: "southern_iberia", name: "Southern Iberia", area: "southern_europe", barren: false, difficultTerrain: [], hasResource: true, x: 0.175, y: 0.542, borders: ["central_massif","northern_apennines","pyrenees","sierra_morena","southern_apennines","western_iberia"], seaBorders: [] },
  { id: "northern_apennines", name: "Northern Apennines", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.248, y: 0.536, borders: ["alps","central_massif","dalmatia","southern_apennines","southern_iberia"], seaBorders: [] },
  { id: "dalmatia", name: "Dalmatia", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.286, y: 0.532, borders: ["alps","balkans","central_europe","danube","northern_apennines","pindus","southern_apennines"], seaBorders: [] },
  { id: "balkans", name: "Balkans", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.321, y: 0.582, borders: ["dalmatia","danube","morea","pindus","western_anatolia"], seaBorders: [] },
  { id: "southern_apennines", name: "Southern Apennines", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.239, y: 0.579, borders: ["dalmatia","morea","northern_apennines","pindus","sierra_morena","southern_iberia"], seaBorders: [] },
  { id: "pindus", name: "Pindus", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.293, y: 0.597, borders: ["balkans","dalmatia","morea","southern_apennines"], seaBorders: [] },
  { id: "morea", name: "Morea", area: "southern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.299, y: 0.624, borders: ["balkans","crete","pindus","southern_apennines","western_anatolia"], seaBorders: [] },
  { id: "sierra_morena", name: "Sierra Morena", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.171, y: 0.645, borders: ["gold_coast","libya","sahara_desert","southern_apennines","southern_iberia","western_iberia"], seaBorders: [] },
  { id: "crete", name: "Crete", area: "southern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.321, y: 0.666, borders: ["levant","morea","nile_delta","palestine","western_anatolia"], seaBorders: [] },
  { id: "highlands", name: "Highlands", area: "northern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.298, y: 0.326, borders: ["albion","ireland"], seaBorders: [] },
  { id: "ireland", name: "Ireland", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.262, y: 0.339, borders: ["albion","highlands","western_gaul"], seaBorders: [] },
  { id: "scandinavia", name: "Scandinavia", area: "northern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.426, y: 0.376, borders: ["albion","baltic_seaboard","north_european_plain"], seaBorders: [] },
  { id: "albion", name: "Albion", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: true, x: 0.299, y: 0.377, borders: ["baltic_seaboard","highlands","ireland","lower_rhine","northern_gaul","scandinavia","western_gaul"], seaBorders: [] },
  { id: "western_gaul", name: "Western Gaul", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.256, y: 0.426, borders: ["albion","alps","central_massif","ireland","northern_gaul","pyrenees"], seaBorders: [] },
  { id: "north_european_plain", name: "North European Plain", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.5, y: 0.427, borders: ["baltic_seaboard","eastern_steppe","scandinavia","siberia","tarim_basin","western_steppe"], seaBorders: [] },
  { id: "lower_rhine", name: "Lower Rhine", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.332, y: 0.461, borders: ["albion","alps","baltic_seaboard","central_europe","danube","northern_gaul"], seaBorders: [] },
  { id: "northern_gaul", name: "Northern Gaul", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.283, y: 0.45, borders: ["albion","alps","lower_rhine","western_gaul"], seaBorders: [] },
  { id: "baltic_seaboard", name: "Baltic-Seaboard", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.385, y: 0.454, borders: ["albion","danube","dnieper","lower_rhine","north_european_plain","scandinavia","western_steppe"], seaBorders: [] },
  { id: "central_europe", name: "Central Europe", area: "northern_europe", barren: false, difficultTerrain: ["forest"], hasResource: true, x: 0.323, y: 0.51, borders: ["alps","dalmatia","danube","lower_rhine"], seaBorders: [] },
  { id: "dnieper", name: "Dnieper", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.407, y: 0.516, borders: ["baltic_seaboard","caucasus","danube","western_steppe"], seaBorders: [] },
  { id: "danube", name: "Danube", area: "northern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.349, y: 0.533, borders: ["balkans","baltic_seaboard","caucasus","central_europe","dalmatia","dnieper","lower_rhine","western_anatolia"], seaBorders: [] },
  { id: "mekong", name: "Mekong", area: "southeast_asia", barren: false, difficultTerrain: [], hasResource: false, x: 0.772, y: 0.527, borders: ["east_indies","irrawaddy","malayan_peninsula","si_kiang","szechwan"], seaBorders: [] },
  { id: "irrawaddy", name: "Irrawaddy", area: "southeast_asia", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.732, y: 0.537, borders: ["ganges_delta","malayan_peninsula","mekong","plateau_of_tibet","szechwan"], seaBorders: [] },
  { id: "east_indies", name: "East Indies", area: "southeast_asia", barren: false, difficultTerrain: [], hasResource: false, x: 0.831, y: 0.616, borders: ["malayan_peninsula","mekong","sumatra"], seaBorders: [] },
  { id: "malayan_peninsula", name: "Malayan Peninsula", area: "southeast_asia", barren: false, difficultTerrain: [], hasResource: true, x: 0.746, y: 0.617, borders: ["east_indies","eastern_deccan","ganges_delta","irrawaddy","mekong","sumatra"], seaBorders: [] },
  { id: "sumatra", name: "Sumatra", area: "southeast_asia", barren: false, difficultTerrain: [], hasResource: false, x: 0.783, y: 0.726, borders: ["ceylon","east_indies","malayan_peninsula","new_guinea","the_outback"], seaBorders: [] },
  { id: "siberia", name: "Siberia", area: "eurasia", barren: true, difficultTerrain: [], hasResource: false, x: 0.56, y: 0.323, borders: ["eastern_steppe","mongolia","north_european_plain"], seaBorders: [] },
  { id: "eastern_steppe", name: "Eastern Steppe", area: "eurasia", barren: false, difficultTerrain: [], hasResource: false, x: 0.615, y: 0.39, borders: ["mongolia","north_european_plain","plateau_of_tibet","siberia","szechwan","tarim_basin","wei_river"], seaBorders: [] },
  { id: "tarim_basin", name: "Tarim Basin", area: "eurasia", barren: false, difficultTerrain: ["mountain"], hasResource: true, x: 0.603, y: 0.463, borders: ["eastern_steppe","north_european_plain","plateau_of_tibet","turanian_plain","western_steppe"], seaBorders: [] },
  { id: "western_steppe", name: "Western Steppe", area: "eurasia", barren: false, difficultTerrain: [], hasResource: false, x: 0.502, y: 0.475, borders: ["baltic_seaboard","caucasus","dnieper","north_european_plain","tarim_basin","turanian_plain"], seaBorders: [] },
  { id: "plateau_of_tibet", name: "Plateau of Tibet", area: "eurasia", barren: true, difficultTerrain: [], hasResource: false, x: 0.66, y: 0.49, borders: ["eastern_steppe","ganges_delta","ganges_valley","irrawaddy","szechwan","tarim_basin"], seaBorders: [] },
  { id: "turanian_plain", name: "Turanian Plain", area: "eurasia", barren: false, difficultTerrain: [], hasResource: false, x: 0.541, y: 0.519, borders: ["caucasus","hindu_kush","persian_plateau","tarim_basin","western_steppe"], seaBorders: [] },
  { id: "mongolia", name: "Mongolia", area: "eurasia", barren: false, difficultTerrain: [], hasResource: false, x: 0.667, y: 0.275, borders: ["eastern_steppe","siberia","wei_river","yellow_river"], seaBorders: [] },
  { id: "northern_lakes", name: "Northern Lakes", area: "north_america", barren: true, difficultTerrain: [], hasResource: false, x: 0.445, y: 0.13, borders: ["appalachia","great_lakes","great_plains","pacific_seaboard"], seaBorders: [] },
  { id: "great_lakes", name: "Great Lakes", area: "north_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.354, y: 0.151, borders: ["appalachia","deep_south","great_plains","northern_lakes"], seaBorders: [] },
  { id: "appalachia", name: "Appalachia", area: "north_america", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.361, y: 0.204, borders: ["deep_south","great_lakes","northern_lakes"], seaBorders: [] },
  { id: "pacific_seaboard", name: "Pacific Seaboard", area: "north_america", barren: false, difficultTerrain: ["mountain"], hasResource: true, x: 0.37, y: 0.058, borders: ["great_plains","mexican_valley","northern_lakes"], seaBorders: [] },
  { id: "great_plains", name: "Great Plains", area: "north_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.358, y: 0.109, borders: ["deep_south","great_lakes","mexican_valley","northern_lakes","pacific_seaboard"], seaBorders: [] },
  { id: "deep_south", name: "Deep South", area: "north_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.312, y: 0.146, borders: ["appalachia","great_lakes","great_plains","mexican_valley","west_indies"], seaBorders: [] },
  { id: "mexican_valley", name: "Mexican Valley", area: "north_america", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.305, y: 0.063, borders: ["central_america","deep_south","great_plains","pacific_seaboard","west_indies"], seaBorders: [] },
  { id: "west_indies", name: "West Indies", area: "north_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.264, y: 0.133, borders: ["central_america","deep_south","guiana_highlands","mexican_valley"], seaBorders: [] },
  { id: "central_america", name: "Central America", area: "north_america", barren: false, difficultTerrain: ["forest"], hasResource: true, x: 0.253, y: 0.1, borders: ["guiana_highlands","mexican_valley","northern_andes","west_indies"], seaBorders: [] },
  { id: "hokkaido", name: "Hokkaido", area: "nippon", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.69, y: 0.078, borders: ["honshu","korea","manchuria"], seaBorders: [] },
  { id: "honshu", name: "Honshu", area: "nippon", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.768, y: 0.08, borders: ["hokkaido","korea"], seaBorders: [] },
  { id: "korea", name: "Korea", area: "nippon", barren: false, difficultTerrain: [], hasResource: false, x: 0.715, y: 0.155, borders: ["great_plain_of_china","hokkaido","honshu","manchuria","yellow_river"], seaBorders: [] },
  { id: "new_guinea", name: "New Guinea", area: "australia", barren: false, difficultTerrain: [], hasResource: false, x: 0.84, y: 0.79, borders: ["australia","sumatra","the_outback"], seaBorders: [] },
  { id: "the_outback", name: "The Outback", area: "australia", barren: true, difficultTerrain: [], hasResource: false, x: 0.792, y: 0.81, borders: ["australia","ceylon","new_guinea","sumatra"], seaBorders: [] },
  { id: "australia", name: "Australia", area: "australia", barren: false, difficultTerrain: [], hasResource: true, x: 0.788, y: 0.859, borders: ["new_guinea","the_outback"], seaBorders: [] },
  { id: "guiana_highlands", name: "Guiana Highlands", area: "south_america", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.184, y: 0.138, borders: ["amazonia","brazil","central_america","northern_andes","west_indies"], seaBorders: [] },
  { id: "brazil", name: "Brazil", area: "south_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.145, y: 0.222, borders: ["amazonia","guiana_highlands","patagonia"], seaBorders: [] },
  { id: "amazonia", name: "Amazonia", area: "south_america", barren: true, difficultTerrain: [], hasResource: false, x: 0.135, y: 0.151, borders: ["brazil","guiana_highlands","northern_andes","patagonia","southern_andes"], seaBorders: [] },
  { id: "northern_andes", name: "Northern Andes", area: "south_america", barren: false, difficultTerrain: ["mountain"], hasResource: true, x: 0.137, y: 0.103, borders: ["amazonia","central_america","guiana_highlands","southern_andes"], seaBorders: [] },
  { id: "southern_andes", name: "Southern Andes", area: "south_america", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.104, y: 0.133, borders: ["amazonia","northern_andes","patagonia"], seaBorders: [] },
  { id: "patagonia", name: "Patagonia", area: "south_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.105, y: 0.195, borders: ["amazonia","brazil","southern_andes"], seaBorders: [] },
]

const LANDS_BY_AREA = new Map<string, LandId[]>()
for (const l of WORLD_LANDS) {
  if (l.area == null) continue
  const list = LANDS_BY_AREA.get(l.area) ?? []
  list.push(l.id)
  LANDS_BY_AREA.set(l.area, list)
}

export const WORLD_AREAS: AreaDef[] = [...LANDS_BY_AREA.keys()].map((id) => ({
  id,
  name: AREA_NAMES[id] ?? id,
  lands: LANDS_BY_AREA.get(id) ?? [],
  valueByEpoch: valueByEpoch(id),
}))

export const WORLD_MAP_DATA: MapData = {
  lands: WORLD_LANDS,
  areas: WORLD_AREAS,
  seas: WORLD_SEAS,
}
