// AUTO-GENERATED by scripts/build-data.mjs from scripts/world.source.json — DO NOT EDIT.
// An ORIGINAL real-geography world map (97 territories across the 13 Areas) faithful
// to the History of the World framework. Geography & historical empires are facts;
// retune by editing world.source.json and re-running the generator.

import type { AreaDef, Land, LandId, MapData, SeaId } from '../types'
import { AREA_NAMES, valueByEpoch } from './areaValues'

export const WORLD_SEAS: SeaId[] = ["adriatic_sea","aegean_sea","arabian_sea","arctic_ocean","atlantic","baltic","bay_of_bengal","bering_sea","black_sea","caribbean","caspian_sea","celebes_sea","coral_sea","east_china_sea","gulf_of_guinea","gulf_of_mexico","indian_ocean","java_sea","mediterranean","mozambique_channel","north_sea","pacific","persian_gulf","red_sea","sea_of_japan","south_china_sea","southern_ocean","tasman_sea","yellow_sea"]

export const WORLD_LANDS: Land[] = [
  { id: "mesopotamia", name: "Mesopotamia", area: "middle_east", barren: false, difficultTerrain: [], hasResource: true, x: 0.622, y: 0.315, borders: ["anatolia","arabia","assyria","empty_quarter","levant","persia","zagros"], seaBorders: ["persian_gulf"] },
  { id: "levant", name: "Levant", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.6, y: 0.314, borders: ["anatolia","arabia","assyria","lower_nile","mesopotamia"], seaBorders: ["mediterranean","red_sea"] },
  { id: "anatolia", name: "Anatolia", area: "middle_east", barren: false, difficultTerrain: ["mountain","strait"], hasResource: false, x: 0.597, y: 0.283, borders: ["assyria","balkans","caucasus","greece","levant","mesopotamia","zagros"], seaBorders: ["black_sea","aegean_sea","mediterranean"] },
  { id: "persia", name: "Persia", area: "middle_east", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.647, y: 0.322, borders: ["caucasus","central_asia","indus","mesopotamia","zagros"], seaBorders: ["persian_gulf","caspian_sea"] },
  { id: "zagros", name: "Zagros", area: "middle_east", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.631, y: 0.311, borders: ["anatolia","assyria","caucasus","mesopotamia","persia"], seaBorders: ["persian_gulf"] },
  { id: "arabia", name: "Arabia", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.625, y: 0.367, borders: ["empty_quarter","ethiopia","levant","mesopotamia"], seaBorders: ["red_sea","persian_gulf","arabian_sea"] },
  { id: "empty_quarter", name: "Empty Quarter", area: "middle_east", barren: true, difficultTerrain: [], hasResource: false, x: 0.639, y: 0.389, borders: ["arabia","mesopotamia"], seaBorders: ["arabian_sea"] },
  { id: "caucasus", name: "Caucasus", area: "middle_east", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.622, y: 0.264, borders: ["anatolia","assyria","persia","pontic_steppe","volga","zagros"], seaBorders: ["black_sea","caspian_sea"] },
  { id: "assyria", name: "Assyria", area: "middle_east", barren: false, difficultTerrain: [], hasResource: false, x: 0.619, y: 0.3, borders: ["anatolia","caucasus","levant","mesopotamia","zagros"], seaBorders: [] },
  { id: "lower_nile", name: "Lower Nile", area: "north_africa", barren: false, difficultTerrain: [], hasResource: true, x: 0.586, y: 0.333, borders: ["levant","libya","upper_nile"], seaBorders: ["mediterranean","red_sea"] },
  { id: "upper_nile", name: "Upper Nile", area: "north_africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.59, y: 0.361, borders: ["east_africa","ethiopia","lower_nile","sahara","west_africa"], seaBorders: ["red_sea"] },
  { id: "libya", name: "Libya", area: "north_africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.55, y: 0.35, borders: ["carthage","lower_nile","sahara"], seaBorders: ["mediterranean"] },
  { id: "carthage", name: "Carthage", area: "north_africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.528, y: 0.297, borders: ["libya","numidia","sahara","sicily"], seaBorders: ["mediterranean"] },
  { id: "numidia", name: "Numidia", area: "north_africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.517, y: 0.306, borders: ["carthage","mauretania","sahara"], seaBorders: ["mediterranean"] },
  { id: "mauretania", name: "Mauretania", area: "north_africa", barren: false, difficultTerrain: ["mountain","strait"], hasResource: false, x: 0.483, y: 0.322, borders: ["iberia","numidia","sahara"], seaBorders: ["mediterranean","atlantic"] },
  { id: "sahara", name: "Sahara", area: "north_africa", barren: true, difficultTerrain: [], hasResource: false, x: 0.514, y: 0.372, borders: ["carthage","libya","mauretania","numidia","upper_nile","west_africa"], seaBorders: ["atlantic"] },
  { id: "north_china", name: "North China", area: "china", barren: false, difficultTerrain: ["great_wall"], hasResource: true, x: 0.819, y: 0.289, borders: ["gobi","korea","manchuria","mongolia","sichuan","south_china","tarim","tibet"], seaBorders: ["yellow_sea","east_china_sea"] },
  { id: "south_china", name: "South China", area: "china", barren: false, difficultTerrain: [], hasResource: true, x: 0.811, y: 0.367, borders: ["burma","indochina","north_china","philippines","ryukyu","sichuan","tibet"], seaBorders: ["south_china_sea","east_china_sea"] },
  { id: "manchuria", name: "Manchuria", area: "china", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.847, y: 0.25, borders: ["korea","mongolia","north_china","siberia"], seaBorders: ["yellow_sea","sea_of_japan"] },
  { id: "tibet", name: "Tibet", area: "china", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.744, y: 0.328, borders: ["burma","central_asia","himalaya","north_china","sichuan","south_china","tarim"], seaBorders: [] },
  { id: "mongolia", name: "Mongolia", area: "china", barren: false, difficultTerrain: [], hasResource: false, x: 0.792, y: 0.244, borders: ["gobi","kazakh_steppe","manchuria","north_china","siberia","tarim"], seaBorders: [] },
  { id: "tarim", name: "Tarim", area: "china", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.733, y: 0.278, borders: ["central_asia","gobi","kazakh_steppe","mongolia","north_china","tibet"], seaBorders: [] },
  { id: "sichuan", name: "Sichuan", area: "china", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.786, y: 0.331, borders: ["burma","north_china","south_china","tibet"], seaBorders: [] },
  { id: "gobi", name: "Gobi", area: "china", barren: true, difficultTerrain: [], hasResource: false, x: 0.778, y: 0.261, borders: ["mongolia","north_china","tarim"], seaBorders: [] },
  { id: "indus", name: "Indus", area: "india", barren: false, difficultTerrain: [], hasResource: true, x: 0.689, y: 0.35, borders: ["deccan","himalaya","persia","punjab"], seaBorders: ["arabian_sea"] },
  { id: "punjab", name: "Punjab", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.706, y: 0.328, borders: ["central_asia","ganges","himalaya","indus"], seaBorders: [] },
  { id: "ganges", name: "Ganges", area: "india", barren: false, difficultTerrain: [], hasResource: true, x: 0.728, y: 0.356, borders: ["bengal","deccan","himalaya","punjab"], seaBorders: ["bay_of_bengal"] },
  { id: "bengal", name: "Bengal", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.747, y: 0.369, borders: ["burma","deccan","ganges","himalaya"], seaBorders: ["bay_of_bengal"] },
  { id: "deccan", name: "Deccan", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.714, y: 0.406, borders: ["bengal","ceylon","ganges","indus"], seaBorders: ["arabian_sea","bay_of_bengal","indian_ocean"] },
  { id: "himalaya", name: "Himalaya", area: "india", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.731, y: 0.339, borders: ["bengal","ganges","indus","punjab","tibet"], seaBorders: [] },
  { id: "ceylon", name: "Ceylon", area: "india", barren: false, difficultTerrain: [], hasResource: false, x: 0.725, y: 0.458, borders: ["deccan"], seaBorders: ["indian_ocean","bay_of_bengal"] },
  { id: "italy", name: "Italy", area: "southern_europe", barren: false, difficultTerrain: [], hasResource: true, x: 0.535, y: 0.27, borders: ["alps","balkans","greece","sicily"], seaBorders: ["mediterranean","adriatic_sea"] },
  { id: "greece", name: "Greece", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.561, y: 0.283, borders: ["anatolia","balkans","crete","italy","sicily"], seaBorders: ["aegean_sea","mediterranean","adriatic_sea"] },
  { id: "iberia", name: "Iberia", area: "southern_europe", barren: false, difficultTerrain: ["mountain","strait"], hasResource: false, x: 0.489, y: 0.278, borders: ["gaul","mauretania"], seaBorders: ["mediterranean","atlantic"] },
  { id: "balkans", name: "Balkans", area: "southern_europe", barren: false, difficultTerrain: ["strait"], hasResource: false, x: 0.558, y: 0.261, borders: ["alps","anatolia","greece","italy","poland","pontic_steppe"], seaBorders: ["adriatic_sea","aegean_sea","black_sea"] },
  { id: "sicily", name: "Sicily", area: "southern_europe", barren: false, difficultTerrain: ["strait"], hasResource: false, x: 0.539, y: 0.292, borders: ["carthage","greece","italy"], seaBorders: ["mediterranean"] },
  { id: "crete", name: "Crete", area: "southern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.569, y: 0.304, borders: ["greece"], seaBorders: ["mediterranean","aegean_sea"] },
  { id: "alps", name: "Alps", area: "southern_europe", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.526, y: 0.242, borders: ["balkans","gaul","germania","italy"], seaBorders: [] },
  { id: "gaul", name: "Gaul", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: true, x: 0.507, y: 0.239, borders: ["alps","britain","germania","iberia","low_countries"], seaBorders: ["atlantic","mediterranean","north_sea"] },
  { id: "britain", name: "Britain", area: "northern_europe", barren: false, difficultTerrain: ["strait"], hasResource: false, x: 0.493, y: 0.205, borders: ["gaul","ireland","low_countries","scandinavia"], seaBorders: ["north_sea","atlantic"] },
  { id: "ireland", name: "Ireland", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.478, y: 0.203, borders: ["britain"], seaBorders: ["atlantic"] },
  { id: "germania", name: "Germania", area: "northern_europe", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.529, y: 0.217, borders: ["alps","gaul","low_countries","poland","scandinavia"], seaBorders: ["north_sea","baltic"] },
  { id: "scandinavia", name: "Scandinavia", area: "northern_europe", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.542, y: 0.156, borders: ["britain","germania","greenland","muscovy","poland"], seaBorders: ["north_sea","baltic","atlantic","arctic_ocean"] },
  { id: "poland", name: "Poland", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.553, y: 0.211, borders: ["balkans","germania","muscovy","pontic_steppe","scandinavia"], seaBorders: ["baltic"] },
  { id: "low_countries", name: "Low Countries", area: "northern_europe", barren: false, difficultTerrain: [], hasResource: false, x: 0.514, y: 0.211, borders: ["britain","gaul","germania"], seaBorders: ["north_sea"] },
  { id: "indochina", name: "Indochina", area: "southeast_asia", barren: false, difficultTerrain: [], hasResource: true, x: 0.794, y: 0.411, borders: ["burma","malaya","siam","south_china"], seaBorders: ["south_china_sea","bay_of_bengal"] },
  { id: "burma", name: "Burma", area: "southeast_asia", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.767, y: 0.383, borders: ["bengal","indochina","siam","sichuan","south_china","tibet"], seaBorders: ["bay_of_bengal"] },
  { id: "siam", name: "Siam", area: "southeast_asia", barren: false, difficultTerrain: [], hasResource: false, x: 0.781, y: 0.417, borders: ["burma","indochina","malaya"], seaBorders: ["south_china_sea","bay_of_bengal"] },
  { id: "malaya", name: "Malaya", area: "southeast_asia", barren: false, difficultTerrain: ["strait"], hasResource: false, x: 0.783, y: 0.478, borders: ["indochina","siam","sumatra"], seaBorders: ["south_china_sea","bay_of_bengal"] },
  { id: "sumatra", name: "Sumatra", area: "southeast_asia", barren: false, difficultTerrain: [], hasResource: false, x: 0.782, y: 0.503, borders: ["borneo","java","malaya"], seaBorders: ["indian_ocean","south_china_sea","java_sea"] },
  { id: "java", name: "Java", area: "southeast_asia", barren: false, difficultTerrain: [], hasResource: true, x: 0.806, y: 0.542, borders: ["borneo","sumatra"], seaBorders: ["java_sea","indian_ocean"] },
  { id: "borneo", name: "Borneo", area: "southeast_asia", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.817, y: 0.497, borders: ["java","philippines","sumatra"], seaBorders: ["south_china_sea","java_sea","celebes_sea"] },
  { id: "philippines", name: "Philippines", area: "southeast_asia", barren: false, difficultTerrain: [], hasResource: false, x: 0.839, y: 0.433, borders: ["borneo","new_guinea","south_china"], seaBorders: ["south_china_sea","pacific","celebes_sea"] },
  { id: "pontic_steppe", name: "Pontic Steppe", area: "eurasia", barren: false, difficultTerrain: [], hasResource: true, x: 0.597, y: 0.233, borders: ["balkans","caucasus","kazakh_steppe","muscovy","poland","volga"], seaBorders: ["black_sea","caspian_sea"] },
  { id: "muscovy", name: "Muscovy", area: "eurasia", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.604, y: 0.19, borders: ["poland","pontic_steppe","scandinavia","siberia","urals","volga"], seaBorders: ["arctic_ocean","baltic"] },
  { id: "volga", name: "Volga", area: "eurasia", barren: false, difficultTerrain: [], hasResource: false, x: 0.631, y: 0.222, borders: ["caucasus","kazakh_steppe","muscovy","pontic_steppe","urals"], seaBorders: ["caspian_sea"] },
  { id: "kazakh_steppe", name: "Kazakh Steppe", area: "eurasia", barren: false, difficultTerrain: [], hasResource: false, x: 0.686, y: 0.233, borders: ["central_asia","mongolia","pontic_steppe","siberia","tarim","urals","volga"], seaBorders: ["caspian_sea"] },
  { id: "central_asia", name: "Central Asia", area: "eurasia", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.678, y: 0.267, borders: ["kazakh_steppe","persia","punjab","tarim","tibet"], seaBorders: ["caspian_sea"] },
  { id: "urals", name: "Urals", area: "eurasia", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.664, y: 0.167, borders: ["kazakh_steppe","muscovy","siberia","volga"], seaBorders: ["arctic_ocean"] },
  { id: "siberia", name: "Siberia", area: "eurasia", barren: true, difficultTerrain: [], hasResource: false, x: 0.778, y: 0.156, borders: ["alaska","hokkaido","kazakh_steppe","manchuria","mongolia","muscovy","urals"], seaBorders: ["arctic_ocean","pacific","sea_of_japan","bering_sea"] },
  { id: "eastern_woodlands", name: "Eastern Woodlands", area: "north_america", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.278, y: 0.278, borders: ["canada","great_plains","mexico","mississippi"], seaBorders: ["atlantic"] },
  { id: "mississippi", name: "Mississippi", area: "north_america", barren: false, difficultTerrain: [], hasResource: true, x: 0.25, y: 0.306, borders: ["eastern_woodlands","great_plains","mexico","rockies"], seaBorders: ["gulf_of_mexico"] },
  { id: "great_plains", name: "Great Plains", area: "north_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.222, y: 0.272, borders: ["canada","eastern_woodlands","mississippi","rockies"], seaBorders: [] },
  { id: "mexico", name: "Mexico", area: "north_america", barren: false, difficultTerrain: ["mountain"], hasResource: true, x: 0.235, y: 0.38, borders: ["caribbean_coast","eastern_woodlands","mississippi","rockies"], seaBorders: ["gulf_of_mexico","caribbean","pacific"] },
  { id: "rockies", name: "Rockies", area: "north_america", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.194, y: 0.256, borders: ["alaska","canada","great_plains","mexico","mississippi"], seaBorders: ["pacific"] },
  { id: "alaska", name: "Alaska", area: "north_america", barren: false, difficultTerrain: ["strait"], hasResource: false, x: 0.078, y: 0.144, borders: ["canada","rockies","siberia"], seaBorders: ["pacific","bering_sea","arctic_ocean"] },
  { id: "canada", name: "Canada", area: "north_america", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.222, y: 0.178, borders: ["alaska","eastern_woodlands","great_plains","greenland","rockies"], seaBorders: ["atlantic","arctic_ocean"] },
  { id: "greenland", name: "Greenland", area: "north_america", barren: true, difficultTerrain: [], hasResource: false, x: 0.383, y: 0.1, borders: ["canada","scandinavia"], seaBorders: ["atlantic","arctic_ocean"] },
  { id: "andes", name: "Andes", area: "south_america", barren: false, difficultTerrain: ["mountain"], hasResource: true, x: 0.285, y: 0.585, borders: ["amazon","caribbean_coast","gran_chaco","pampas","patagonia"], seaBorders: ["pacific"] },
  { id: "amazon", name: "Amazon", area: "south_america", barren: true, difficultTerrain: [], hasResource: false, x: 0.328, y: 0.522, borders: ["andes","brazil","caribbean_coast","gran_chaco"], seaBorders: ["atlantic"] },
  { id: "brazil", name: "Brazil", area: "south_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.361, y: 0.556, borders: ["amazon","caribbean_coast","gran_chaco","pampas"], seaBorders: ["atlantic"] },
  { id: "pampas", name: "Pampas", area: "south_america", barren: false, difficultTerrain: [], hasResource: true, x: 0.328, y: 0.694, borders: ["andes","brazil","gran_chaco","patagonia"], seaBorders: ["atlantic"] },
  { id: "gran_chaco", name: "Gran Chaco", area: "south_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.331, y: 0.628, borders: ["amazon","andes","brazil","pampas"], seaBorders: [] },
  { id: "patagonia", name: "Patagonia", area: "south_america", barren: false, difficultTerrain: ["strait"], hasResource: false, x: 0.308, y: 0.75, borders: ["andes","antarctica","pampas"], seaBorders: ["atlantic","pacific","southern_ocean"] },
  { id: "caribbean_coast", name: "Caribbean Coast", area: "south_america", barren: false, difficultTerrain: [], hasResource: false, x: 0.303, y: 0.45, borders: ["amazon","andes","brazil","mexico"], seaBorders: ["caribbean","atlantic","pacific"] },
  { id: "antarctica", name: "Antarctica", area: "south_america", barren: true, difficultTerrain: [], hasResource: false, x: 0.325, y: 0.92, borders: ["patagonia"], seaBorders: ["southern_ocean","atlantic","pacific"] },
  { id: "honshu", name: "Honshu", area: "nippon", barren: false, difficultTerrain: ["mountain"], hasResource: true, x: 0.886, y: 0.3, borders: ["hokkaido","korea","kyushu","shikoku"], seaBorders: ["sea_of_japan","pacific"] },
  { id: "kyushu", name: "Kyushu", area: "nippon", barren: false, difficultTerrain: ["strait"], hasResource: false, x: 0.864, y: 0.319, borders: ["honshu","korea","ryukyu","shikoku"], seaBorders: ["east_china_sea","sea_of_japan","pacific"] },
  { id: "shikoku", name: "Shikoku", area: "nippon", barren: false, difficultTerrain: [], hasResource: false, x: 0.871, y: 0.313, borders: ["honshu","kyushu"], seaBorders: ["pacific"] },
  { id: "hokkaido", name: "Hokkaido", area: "nippon", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.897, y: 0.259, borders: ["honshu","siberia"], seaBorders: ["sea_of_japan","pacific"] },
  { id: "korea", name: "Korea", area: "nippon", barren: false, difficultTerrain: ["strait","mountain"], hasResource: false, x: 0.854, y: 0.294, borders: ["honshu","kyushu","manchuria","north_china"], seaBorders: ["yellow_sea","sea_of_japan","east_china_sea"] },
  { id: "ryukyu", name: "Ryukyu", area: "nippon", barren: false, difficultTerrain: [], hasResource: false, x: 0.856, y: 0.353, borders: ["kyushu","south_china"], seaBorders: ["east_china_sea","pacific"] },
  { id: "west_africa", name: "West Africa", area: "africa", barren: false, difficultTerrain: [], hasResource: true, x: 0.489, y: 0.422, borders: ["congo","guinea_coast","sahara","upper_nile"], seaBorders: ["atlantic"] },
  { id: "guinea_coast", name: "Guinea Coast", area: "africa", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.506, y: 0.467, borders: ["congo","west_africa"], seaBorders: ["atlantic","gulf_of_guinea"] },
  { id: "ethiopia", name: "Ethiopia", area: "africa", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.608, y: 0.45, borders: ["arabia","east_africa","great_lakes","upper_nile"], seaBorders: ["red_sea","indian_ocean"] },
  { id: "east_africa", name: "East Africa", area: "africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.603, y: 0.511, borders: ["congo","ethiopia","great_lakes","upper_nile","zimbabwe"], seaBorders: ["indian_ocean"] },
  { id: "congo", name: "Congo", area: "africa", barren: false, difficultTerrain: ["forest"], hasResource: false, x: 0.561, y: 0.506, borders: ["cape","east_africa","great_lakes","guinea_coast","west_africa","zimbabwe"], seaBorders: ["atlantic"] },
  { id: "great_lakes", name: "Great Lakes", area: "africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.583, y: 0.517, borders: ["congo","east_africa","ethiopia","zimbabwe"], seaBorders: [] },
  { id: "zimbabwe", name: "Zimbabwe", area: "africa", barren: false, difficultTerrain: [], hasResource: true, x: 0.582, y: 0.606, borders: ["cape","congo","east_africa","great_lakes"], seaBorders: ["indian_ocean","mozambique_channel"] },
  { id: "cape", name: "Cape", area: "africa", barren: false, difficultTerrain: [], hasResource: false, x: 0.564, y: 0.7, borders: ["congo","zimbabwe"], seaBorders: ["atlantic","indian_ocean","southern_ocean"] },
  { id: "eastern_australia", name: "Eastern Australia", area: "australia", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.917, y: 0.685, borders: ["new_guinea","new_zealand","outback","polynesia","tasmania","western_australia"], seaBorders: ["coral_sea","tasman_sea","pacific"] },
  { id: "western_australia", name: "Western Australia", area: "australia", barren: false, difficultTerrain: [], hasResource: false, x: 0.839, y: 0.639, borders: ["eastern_australia","outback"], seaBorders: ["indian_ocean"] },
  { id: "outback", name: "Outback", area: "australia", barren: true, difficultTerrain: [], hasResource: false, x: 0.872, y: 0.639, borders: ["eastern_australia","western_australia"], seaBorders: [] },
  { id: "new_guinea", name: "New Guinea", area: "australia", barren: false, difficultTerrain: ["forest","mountain"], hasResource: false, x: 0.892, y: 0.528, borders: ["eastern_australia","philippines","polynesia"], seaBorders: ["coral_sea","pacific"] },
  { id: "new_zealand", name: "New Zealand", area: "australia", barren: false, difficultTerrain: ["mountain"], hasResource: false, x: 0.983, y: 0.728, borders: ["eastern_australia","polynesia","tasmania"], seaBorders: ["tasman_sea","pacific","southern_ocean"] },
  { id: "tasmania", name: "Tasmania", area: "australia", barren: false, difficultTerrain: [], hasResource: false, x: 0.908, y: 0.733, borders: ["eastern_australia","new_zealand"], seaBorders: ["tasman_sea","southern_ocean","pacific"] },
  { id: "polynesia", name: "Polynesia", area: "australia", barren: false, difficultTerrain: [], hasResource: false, x: 0.989, y: 0.6, borders: ["eastern_australia","new_guinea","new_zealand"], seaBorders: ["pacific","coral_sea"] },
]

const LANDS_BY_AREA = new Map<string, LandId[]>()
for (const l of WORLD_LANDS) {
  if (l.area == null) continue
  const list = LANDS_BY_AREA.get(l.area) ?? []
  list.push(l.id)
  LANDS_BY_AREA.set(l.area, list)
}

export const WORLD_AREAS: AreaDef[] = [...LANDS_BY_AREA.keys()].map((id) => ({
  id,
  name: AREA_NAMES[id] ?? id,
  lands: LANDS_BY_AREA.get(id) ?? [],
  valueByEpoch: valueByEpoch(id),
}))

export const WORLD_MAP_DATA: MapData = {
  lands: WORLD_LANDS,
  areas: WORLD_AREAS,
  seas: WORLD_SEAS,
}
