#!/usr/bin/env node
// Embed the curated OFL fonts as base64, subset to Latin, into a committed data
// module (src/data/fonts-data.ts). The SAME base64 bytes drive both the on-screen
// @font-face preview and jsPDF (addFileToVFS/addFont), so the printed PDF matches
// the design on any machine — fully offline, no fetch().
//
//   npm run embed:fonts
//
// Requires the build venv with fonttools:  .fontvenv/bin/pyftsubset
// Source TTFs come from @expo-google-fonts/* devDependencies.

import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DATA_DIR = resolve(ROOT, 'src/data');
const NM = resolve(ROOT, 'node_modules/@expo-google-fonts');
const PYFTSUBSET = resolve(ROOT, '.fontvenv/bin/pyftsubset');
const TMP = resolve(ROOT, '.font-tmp.ttf');

// Latin: ASCII, Latin-1 supplement, smart quotes/dashes, ellipsis, bullet.
const UNICODES = [
  'U+0020-007E',
  'U+00A0-00FF',
  'U+2013-2014', // en/em dash
  'U+2018-2019', // ' '
  'U+201C-201D', // " "
  'U+2022', // bullet
  'U+2026', // ellipsis
  'U+2122', // ™
].join(',');

// key, label, cssFamily (unique to avoid clashing with any installed system font),
// category, and source TTF per jsPDF style.
const FONTS = [
  { key: 'inter', label: 'Inter', cssFamily: 'CM Inter', category: 'sans', files: { normal: 'inter/400Regular/Inter_400Regular.ttf', bold: 'inter/700Bold/Inter_700Bold.ttf' } },
  { key: 'montserrat', label: 'Montserrat', cssFamily: 'CM Montserrat', category: 'sans', files: { normal: 'montserrat/400Regular/Montserrat_400Regular.ttf', bold: 'montserrat/700Bold/Montserrat_700Bold.ttf' } },
  { key: 'nunito', label: 'Nunito', cssFamily: 'CM Nunito', category: 'sans', files: { normal: 'nunito/400Regular/Nunito_400Regular.ttf', bold: 'nunito/700Bold/Nunito_700Bold.ttf' } },
  { key: 'lora', label: 'Lora', cssFamily: 'CM Lora', category: 'serif', files: { normal: 'lora/400Regular/Lora_400Regular.ttf', bold: 'lora/700Bold/Lora_700Bold.ttf' } },
  { key: 'merriweather', label: 'Merriweather', cssFamily: 'CM Merriweather', category: 'serif', files: { normal: 'merriweather/400Regular/Merriweather_400Regular.ttf', bold: 'merriweather/700Bold/Merriweather_700Bold.ttf' } },
  { key: 'playfair', label: 'Playfair Display', cssFamily: 'CM Playfair', category: 'serif', files: { normal: 'playfair-display/400Regular/PlayfairDisplay_400Regular.ttf', bold: 'playfair-display/700Bold/PlayfairDisplay_700Bold.ttf' } },
  { key: 'caveat', label: 'Caveat', cssFamily: 'CM Caveat', category: 'handwriting', files: { normal: 'caveat/400Regular/Caveat_400Regular.ttf', bold: 'caveat/700Bold/Caveat_700Bold.ttf' } },
  { key: 'dancing', label: 'Dancing Script', cssFamily: 'CM Dancing Script', category: 'script', files: { normal: 'dancing-script/400Regular/DancingScript_400Regular.ttf', bold: 'dancing-script/700Bold/DancingScript_700Bold.ttf' } },
  { key: 'pacifico', label: 'Pacifico', cssFamily: 'CM Pacifico', category: 'display', files: { normal: 'pacifico/400Regular/Pacifico_400Regular.ttf' } },
];

if (!existsSync(PYFTSUBSET)) {
  console.error(`! pyftsubset not found at ${PYFTSUBSET}\n  Create the build venv:\n    python3 -m venv .fontvenv && ./.fontvenv/bin/pip install fonttools brotli`);
  process.exit(1);
}

function subsetToBase64(srcRel) {
  const src = resolve(NM, srcRel);
  if (!existsSync(src)) throw new Error(`missing source font: ${src}`);
  execFileSync(PYFTSUBSET, [
    src,
    `--unicodes=${UNICODES}`,
    '--layout-features=*',
    '--no-hinting',
    '--desubroutinize',
    `--output-file=${TMP}`,
    '--flavor=', // plain TTF (jsPDF needs raw TTF/OTF, not woff)
  ]);
  const b64 = readFileSync(TMP).toString('base64');
  rmSync(TMP, { force: true });
  return b64;
}

const fontFiles = {}; // key -> { style -> base64 }
const registry = []; // metadata for the hand-written fonts.ts
let totalBytes = 0;

for (const f of FONTS) {
  fontFiles[f.key] = {};
  const styles = [];
  for (const [style, rel] of Object.entries(f.files)) {
    const b64 = subsetToBase64(rel);
    fontFiles[f.key][style] = b64;
    styles.push(style);
    totalBytes += Math.floor((b64.length * 3) / 4);
  }
  registry.push({ key: f.key, label: f.label, cssFamily: f.cssFamily, category: f.category, styles });
  console.log(`  ${f.label}: ${styles.join(', ')}`);
}

mkdirSync(DATA_DIR, { recursive: true });

const dataOut =
  `// GENERATED by scripts/embed-fonts.mjs — do not edit by hand.\n` +
  `// OFL fonts (@expo-google-fonts/*), subset to Latin, base64-encoded.\n` +
  `// key -> jsPDF style ('normal'|'bold'|...) -> base64 TTF.\n\n` +
  `export const FONT_FILES: Record<string, Record<string, string>> = ${JSON.stringify(fontFiles)};\n`;
writeFileSync(resolve(DATA_DIR, 'fonts-data.ts'), dataOut);

const regOut =
  `// GENERATED by scripts/embed-fonts.mjs — do not edit by hand.\n` +
  `// Font metadata (display label, CSS family, category, available styles).\n\n` +
  `export interface EmbeddedFontMeta {\n` +
  `  key: string;\n  label: string;\n  cssFamily: string;\n` +
  `  category: 'sans' | 'serif' | 'script' | 'display' | 'handwriting' | 'mono';\n` +
  `  styles: string[];\n}\n\n` +
  `export const FONT_REGISTRY: EmbeddedFontMeta[] = ${JSON.stringify(registry, null, 2)};\n`;
writeFileSync(resolve(DATA_DIR, 'fonts-registry.ts'), regOut);

console.log(`\n✓ Embedded ${FONTS.length} fonts (~${Math.round(totalBytes / 1024)} KB of TTF) → src/data/fonts-data.ts + fonts-registry.ts`);
