#!/usr/bin/env node
// Ingest the curated content sources into committed, build-reproducible data modules:
//
//   ~/Downloads/nasb.txt            -> src/data/bible-data.ts   (full NASB tree)
//   ~/Downloads/tlc_quotes_seed.json -> src/data/sayings-data.ts (sayings catalog)
//
// Browsers block fetch() of sibling files from file://, so this content must be
// compiled into the single-file build. Run once (or whenever the sources change):
//   npm run ingest:content
// Override source paths:  node scripts/ingest-content.mjs --bible <path> --quotes <path>

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DATA_DIR = resolve(ROOT, 'src/data');

function arg(flag, fallback) {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const BIBLE_SRC = arg('--bible', resolve(homedir(), 'Downloads/nasb.txt'));
const QUOTES_SRC = arg('--quotes', resolve(homedir(), 'Downloads/tlc_quotes_seed.json'));

const SMALL_WORDS = new Set(['of', 'the']);
function titleCaseBook(name) {
  return name
    .split(/\s+/)
    .map((w, i) =>
      /^\d/.test(w)
        ? w
        : i > 0 && SMALL_WORDS.has(w.toLowerCase())
          ? w.toLowerCase()
          : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase(),
    )
    .join(' ');
}

function ingestBible() {
  if (!existsSync(BIBLE_SRC)) {
    console.error(`! Bible source not found: ${BIBLE_SRC} (skipping bible ingest)`);
    return false;
  }
  const raw = readFileSync(BIBLE_SRC, 'utf8');
  const lines = raw.split(/\r?\n/);

  /** @type {string[]} canonical book order, first-seen */
  const bookOrder = [];
  /** @type {Record<string, string[][]>} display book -> chapters[ch-1] -> verses[v-1] */
  const tree = {};
  let count = 0;

  for (const line of lines) {
    const t = line.trim();
    if (!t || t === '.') continue;
    const sep = t.lastIndexOf(' -- ');
    if (sep < 0) continue;
    const text = t.slice(0, sep).trim();
    const ref = t.slice(sep + 4).trim();
    const m = /^(.+) (\d+):(\d+)$/.exec(ref);
    if (!m) {
      console.warn(`  ? unparseable reference, skipped: "${ref}"`);
      continue;
    }
    const book = titleCaseBook(m[1]);
    const ch = parseInt(m[2], 10);
    const v = parseInt(m[3], 10);
    if (!tree[book]) {
      tree[book] = [];
      bookOrder.push(book);
    }
    while (tree[book].length < ch) tree[book].push([]);
    const chapter = tree[book][ch - 1];
    while (chapter.length < v) chapter.push('');
    chapter[v - 1] = text;
    count++;
  }

  const out =
    `// GENERATED by scripts/ingest-content.mjs — do not edit by hand.\n` +
    `// Source: ${BIBLE_SRC}\n` +
    `// ${count} verses across ${bookOrder.length} books.\n\n` +
    `export const BIBLE_BOOKS: string[] = ${JSON.stringify(bookOrder)};\n\n` +
    `// book -> chapters (index = chapter-1) -> verses (index = verse-1) -> text\n` +
    `export const BIBLE: Record<string, string[][]> = ${JSON.stringify(tree)};\n`;

  mkdirSync(DATA_DIR, { recursive: true });
  writeFileSync(resolve(DATA_DIR, 'bible-data.ts'), out);
  console.log(`✓ bible-data.ts: ${count} verses, ${bookOrder.length} books`);
  return true;
}

function ingestQuotes() {
  if (!existsSync(QUOTES_SRC)) {
    console.error(`! Quotes source not found: ${QUOTES_SRC} (skipping sayings ingest)`);
    return false;
  }
  const data = JSON.parse(readFileSync(QUOTES_SRC, 'utf8'));
  const author = data?.meta?.subject || 'Unknown';
  const quotes = Array.isArray(data?.quotes) ? data.quotes : [];
  const entries = quotes
    .filter((q) => q && typeof q.quote === 'string' && q.quote.trim())
    .map((q) => ({
      id: String(q.id || ''),
      kind: 'saying',
      text: q.quote.trim(),
      reference: author,
    }));

  const out =
    `// GENERATED by scripts/ingest-content.mjs — do not edit by hand.\n` +
    `// Source: ${QUOTES_SRC}\n` +
    `// ${entries.length} sayings.\n\n` +
    `import type { FillerEntry } from '../model/types';\n\n` +
    `export const SAYINGS: FillerEntry[] = ${JSON.stringify(entries, null, 2)};\n`;

  mkdirSync(DATA_DIR, { recursive: true });
  writeFileSync(resolve(DATA_DIR, 'sayings-data.ts'), out);
  console.log(`✓ sayings-data.ts: ${entries.length} sayings (author: ${author})`);
  return true;
}

const okB = ingestBible();
const okQ = ingestQuotes();
if (!okB || !okQ) {
  console.error('\nContent ingest incomplete — see messages above.');
  process.exit(1);
}
console.log('\nContent ingest complete.');
