import Foundation
import GRDB

/// The Matter — one row per tracked unit of work. The primary key is the
/// human-readable Matter ID (`YYYY-MM-DD-#####`) generated by
/// `MatterIDService`. All free-text long-form fields are markdown.
struct Matter: Codable, Hashable, Identifiable, FetchableRecord, MutablePersistableRecord {
    static let databaseTableName = "matter"

    var id: String                          // Matter ID, e.g. "2026-05-07-00001"
    var title: String
    var typeId: String                      // FK matter_type.id
    var status: String                      // MatterStatus.rawValue (string for user-renamability)
    var descriptionMd: String
    var dueAt: Date?
    var createdAt: Date
    var accessedAt: Date
    var modifiedAt: Date

    var external1Number: String
    var external1Url: String
    var external2Number: String
    var external2Url: String
    var external3Number: String
    var external3Url: String
    var timeTrackingCode: String

    var resolutionMd: String
    var lessonsMd: String
    var notesMd: String                     // free-form markdown notes; the timestamped `note` rows are separate

    var fileStorePrimary: String
    var fileStoreSecondary: String

    var cadenceId: String?                  // FK cadence.id (nullable; only set for cadenced Matters)
    var parentMatterId: String?             // links a cadence-spawned Matter to its predecessor
    var requestorAssociateId: String        // FK person.id ("" = no requestor assigned)
    var priority: String                    // MatterPriority.rawValue (e.g. "P3 Medium")

    // Interested Parties — internal company people (FK person.id, "" = unset).
    // Five fixed slots so we can address them with stable bindings in the UI.
    var interestedParty1AssociateId: String
    var interestedParty2AssociateId: String
    var interestedParty3AssociateId: String
    var interestedParty4AssociateId: String
    var interestedParty5AssociateId: String

    // External Interested Parties — free text (e.g. third-party contact names),
    // not tied to the People roster.
    var externalInterestedParty1: String
    var externalInterestedParty2: String
    var externalInterestedParty3: String
    var externalInterestedParty4: String
    var externalInterestedParty5: String

    /// Soft-delete tombstone. nil → live Matter. Set → in Trash; the
    /// 30-day purge sweep on launch hard-deletes anything older than that.
    var deletedAt: Date?

    /// Optional Third Party link. NULL when the Matter isn't tied to a vendor.
    /// `ON DELETE SET NULL` at the DB level so vendor hard-delete is safe.
    var vendorId: String?

    enum CodingKeys: String, CodingKey {
        case id, title, status
        case typeId = "type_id"
        case descriptionMd = "description_md"
        case dueAt = "due_at"
        case createdAt = "created_at"
        case accessedAt = "accessed_at"
        case modifiedAt = "modified_at"
        case external1Number = "external1_number"
        case external1Url = "external1_url"
        case external2Number = "external2_number"
        case external2Url = "external2_url"
        case external3Number = "external3_number"
        case external3Url = "external3_url"
        case timeTrackingCode = "time_tracking_code"
        case resolutionMd = "resolution_md"
        case lessonsMd = "lessons_md"
        case notesMd = "notes_md"
        case fileStorePrimary = "file_store_primary"
        case fileStoreSecondary = "file_store_secondary"
        case cadenceId = "cadence_id"
        case parentMatterId = "parent_matter_id"
        case requestorAssociateId = "requestor_associate_id"
        case priority
        case interestedParty1AssociateId = "interested_party1_associate_id"
        case interestedParty2AssociateId = "interested_party2_associate_id"
        case interestedParty3AssociateId = "interested_party3_associate_id"
        case interestedParty4AssociateId = "interested_party4_associate_id"
        case interestedParty5AssociateId = "interested_party5_associate_id"
        case externalInterestedParty1 = "external_interested_party1"
        case externalInterestedParty2 = "external_interested_party2"
        case externalInterestedParty3 = "external_interested_party3"
        case externalInterestedParty4 = "external_interested_party4"
        case externalInterestedParty5 = "external_interested_party5"
        case deletedAt = "deleted_at"
        case vendorId = "vendor_id"
    }

    static func newDraft(id: String, typeId: String, title: String = "") -> Matter {
        let now = Date()
        return Matter(
            id: id,
            title: title,
            typeId: typeId,
            status: MatterStatus.new.rawValue,
            descriptionMd: "",
            dueAt: nil,
            createdAt: now,
            accessedAt: now,
            modifiedAt: now,
            external1Number: "",
            external1Url: "",
            external2Number: "",
            external2Url: "",
            external3Number: "",
            external3Url: "",
            timeTrackingCode: "",
            resolutionMd: "",
            lessonsMd: "",
            notesMd: "",
            fileStorePrimary: "",
            fileStoreSecondary: "",
            cadenceId: nil,
            parentMatterId: nil,
            requestorAssociateId: "",
            priority: MatterPriority.defaultPriority.rawValue,
            interestedParty1AssociateId: "",
            interestedParty2AssociateId: "",
            interestedParty3AssociateId: "",
            interestedParty4AssociateId: "",
            interestedParty5AssociateId: "",
            externalInterestedParty1: "",
            externalInterestedParty2: "",
            externalInterestedParty3: "",
            externalInterestedParty4: "",
            externalInterestedParty5: "",
            deletedAt: nil,
            vendorId: nil
        )
    }
}
